### PR TITLE
Compatibility with Jandex 3

### PR DESCRIPTION
**Pull request by Ladicek**
This PR replaces the usage of `ClassInfo.annotations()` with `ClassInfo.annotationsMap()`, because `annotations()` have different meaning between Jandex 2 and 3 (while `annotationsMap()`, added in Jandex 2.4.3, has the same meaning in Jandex 3.0).

Also, this PR removes the dependency on `org.jboss:jandex` from the `runtime` module of the Quarkus extension, because that seems completely unnecessary. Jandex is almost never required at runtime in Quarkus applications, and I couldn't find any evidence of OptaPlanner using Jandex (besides the `deployment` part of the Quarkus extension, of course).

Sorry if I'm submitting this PR incorrectly, I never contributed to OptaPlanner before. I'm happy to do any adjustments necessary.

### JIRA

None

### Referenced pull requests

N/A

### Checklist
- [ ] Documentation updated if applicable.
- [ ] Upgrade recipe provided if applicable.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  please add comment: <b>Jenkins (re)run [optaplanner|optaplanner-quickstarts|optaweb-vehicle-routing] tests</b>
  
- for a <b>full downstream build</b> 
  - for <b>jenkins</b> job: 
    please add comment: <b>Jenkins run fdb</b>
  - for <b>github actions</b> job: 
    add the label `run_fdb`

- for a <b>compile downstream build</b>  
  please add comment: <b>Jenkins run cdb</b>

- for a <b>full production downstream build</b>  
  please add comment: <b>Jenkins execute product fdb</b>

- for an <b>upstream build</b>  
  please add comment: <b>Jenkins run upstream</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [optaplanner|optaplanner-quickstarts|optaweb-vehicle-routing] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [optaplanner|optaplanner-quickstarts|optaweb-vehicle-routing] quarkus-branch</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [optaplanner|optaplanner-quickstarts|optaweb-vehicle-routing] native</b>

- for <b>mandrel checks</b>  
  Run native checks against Mandrel image
  Please add comment: <b>Jenkins run mandrel</b>

- for a <b>specific mandrel check</b>  
  Run native checks against Mandrel image  
  Please add comment: <b>Jenkins (re)run [optaplanner|optaplanner-quickstarts|optaweb-vehicle-routing] mandrel</b>
</details>

### CI Status

 You can check OptaPlanner repositories CI status from [Chain Status webpage](https://kiegroup.github.io/optaplanner/).

### CODE REVIEW

**Comment by Christopher-Chianelli** [comment]
ok to test

**Comment by Ladicek** [comment]
There's some bytecode generation stuff in the `deployment` module, and that does seem to use Jandex. However, that doesn't require the `runtime` module to depend on Jandex (which ends up putting Jandex on the runtime classpath of the Quarkus application), and `deployment` module gets Jandex transitively from the core Quarkus dependencies anyway.

**Comment by Christopher-Chianelli** [comment]
@Ladicek the bytecode generation I was talking about is in `optaplanner-core`, and it did directly use Jandex at one time (I was adding historical context). In particular, previously, there was two routes: in normal Java, the Method/Field instance was used directly, and in Quarkus, FieldInfo/MethodInfo was used. Now, `io.quarkus.gizmo.FieldDescriptor` amd `io.quarkus.gizmo.MethodDescriptor` is used instead of Jandex `FieldInfo` and `MethodInfo`.

**Comment by Ladicek** [comment]
Ah, I see. Thanks for info!

**Review by triceo — APPROVED** [review]

**Comment by triceo** [comment]
Jenkins run native tests.

**Comment by triceo** [comment]
Thanks for the contribution, @Ladicek!

Normally we'd ask you to file a JIRA for each PR, but considering the size and scope of this PR, I decided to let it slide. :)

**Comment by ge0ffrey** [comment]
This breaks our compatibility with Quarkus 2.7. (Just detected by CI)

Is there any way for us to be compatible with both Quarkus 2.7 and Quarkus 2.13?

@ibek ^^ The upcoming OptaPlanner community releases are currently not compatible with Quarkus 2.7. Please track this, as its a risk.

**Comment by Ladicek** [comment]
Quarkus 2.13 doesn't upgrade to Jandex 3, so for compatibility with Quarkus 2.13, you can just revert this PR. This change is needed for Quarkus 2.14+.

**Comment by ge0ffrey** [comment]
Thank you Ladicek, Good to know.

**Comment by Ladicek** [comment]
Sorry for not making this clear from the beginning. I don't know what your branching/release strategy is, so I trust you do what's right :-)

**Pull request merged**
