### PR TITLE
[8.13.x] Bump Quarkus version to 2.13.4.Final (#2303)

### PR DESCRIPTION
**Pull request by cristianonicolai**
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/2820
- https://github.com/kiegroup/kogito-apps/pull/1639
- https://github.com/kiegroup/kogito-examples/pull/1581
- https://github.com/kiegroup/optaplanner/pull/2639
- https://github.com/kiegroup/optaplanner-quickstarts/pull/522

### CODE REVIEW

**Comment by kie-ci1** [comment]
**(tests) - optaplanner-quickstarts job** `#19` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/optaplanner.tests.downstream.optaplanner-quickstarts/19/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-02-27T09:52:48.574Z] du: cannot access ‘/home/jenkins/workspace/KIE/optaplanner/8.35.x/setup-branch/optaweb-vehicle-routing_ws-cleanup_1677491564538/optaweb-vehicle-routing/optaweb-vehicle-routing-frontend/node_modules/webpack-dev-server/client/utils/log.js’: No such file or directory<br/>[2023-02-27T09:52:48.574Z] du: cannot access ‘/home/jenkins/workspace/KIE/optaplanner/8.35.x/setup-branch/optaweb-vehicle-routing_ws-cleanup_1677491564538/optaweb-vehicle-routing/optaweb-vehicle-routing-frontend/node_modules/webpack-dev-server/client/utils/parseURL.js’: No such file or directory<br/>[2023-02-27T09:52:48.574Z] du: cannot access ‘/home/jenkins/workspace/KIE/optaplanner/8.35.x/setup-branch/optaweb-vehicle-routing_ws-cleanup_1677491564538/optaweb-vehicle-routing/optaweb-vehicle-routing-frontend/node_modules/webpack-dev-server/client/utils/reloadApp.js’: No such file or directory<br/>[2023-02-27T09:52:48.574Z] du: cannot access ‘/home/jenkins/workspace/KIE/optaplanner/8.35.x/setup-branch/optaweb-vehicle-routing_ws-cleanup_1677491564538/optaweb-vehicle-routing/optaweb-vehicle-routing-frontend/node_modules/webpack-dev-server/client/utils/sendMessage.js’: No such file or directory<br/>[2023-02-27T09:52:48.574Z] du: cannot access ‘/home/jenkins/workspace/KIE/optaplanner/8.35.x/setup-branch/optaweb-vehicle-routing_ws-cleanup_1677491564538/optaweb-vehicle-routing/optaweb-vehicle-routing-frontend/node_modules/webpack-dev-server/client/utils/stripAnsi.js’: No such file or directory<br/>[2023-02-27T09:52:48.574Z] du: cannot access ‘/home/jenkins/workspace/KIE/optaplanner/8.35.x/setup-branch/optaweb-vehicle-routing_ws-cleanup_1677491564538/optaweb-vehicle-routing/optaweb-vehicle-routing-frontend/node_modules/webpack-dev-server/client/index.js’: No such file or directory<br/>[2023-02-27T09:52:48.574Z] 1.6G	/home/jenkins/workspace<br/>[2023-02-27T09:52:48.574Z] 0	/home/jenkins/.pki<br/>[2023-02-27T09:52:48.574Z] 119M	/home/jenkins/tools<br/>[2023-02-27T09:52:48.574Z] 0	/home/jenkins/caches<br/>[2023-02-27T09:52:48.574Z] 91M	/home/jenkins/.npm<br/>[2023-02-27T09:52:48.574Z] 8.0K	/home/jenkins/.java<br/>[2023-02-27T09:52:48.574Z] 8.0K	/home/jenkins/.docker<br/>[2023-02-27T09:52:48.574Z] 4.1G	/home/jenkins<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Install build-chain tool)<br/>Stage "Install build-chain tool" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>Stage "Build projects" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Sonar analysis)<br/>Stage "Sonar analysis" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space after build)<br/>Stage "check space after build" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2023-02-27T09:52:49.432Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/optaplanner.tests.downstream.optaplanner-quickstarts/19/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by cristianonicolai** [comment]
Jenkins rerun optaplanner-quickstarts tests

**Comment by cristianonicolai** [comment]
Jenkins retest optaplanner-quickstarts

**Comment by cristianonicolai** [comment]
jenkins please retest optaplanner-quickstarts

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by radtriste** [comment]
Jenkins run optaplanner-quickstarts tests

**Comment by radtriste** [comment]
Jenkins run optaplanner-quickstarts tests

**Comment by mbiarnes** [comment]
Jenkins run optaplanner-quickstarts tests

**Comment by radtriste** [comment]
Jenkins run optaplanner-quickstarts tests

**Comment by mbiarnes** [comment]
Jenkins run optaplanner-quickstarts tests

**Review by radtriste — APPROVED** [review]

**Review by rsynek — APPROVED** [review]

**Pull request merged**
