### PR TITLE
PLANNER-2467 Jenkinsfiles moved to .ci/jenkins

### PR DESCRIPTION
**Pull request by Ginxo**
**Thank you for submitting this pull request**

**JIRA**: https://issues.redhat.com/browse/PLANNER-2467

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_
* https://github.com/kiegroup/kie-jenkins-scripts/pull/1025
* https://github.com/jboss-integration/rhba/pull/42
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1688
* https://github.com/kiegroup/optaweb-vehicle-routing/pull/526
* https://github.com/kiegroup/optaweb-employee-rostering/pull/651
* https://github.com/kiegroup/optaplanner/pull/1414
* https://github.com/kiegroup/kogito-runtimes/pull/1428

### Checklist
- [ ] Documentation updated if applicable.
- [ ] Upgrade recipe provided if applicable.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>specific pull request build</b> please add comment: <b>Jenkins (re)run [optaplanner|apps|examples] tests</b>
* for a <b>full downstream build</b> please add comment: <b>Jenkins run fdb</b>
* for a <b>compile downstream build</b> please add comment: <b>Jenkins run cdb</b>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* for an <b>upstream build</b> please add comment: <b>Jenkins run upstream</b>
* for a <b>Quarkus LTS check</b> please add comment: <b>Jenkins run LTS</b>
* for a <b>specific Quarkus LTS check</b> please add comment: <b>Jenkins (re)run [optaplanner|apps|examples] LTS</b>
* for a <b>Native check</b> please add comment: <b>Jenkins run native</b>
* for a <b>specific Native LTS check</b> please add comment: <b>Jenkins (re)run [optaplanner|apps|examples] native</b>
</details>

> Great stuff! Let's get this merged.
> @Ginxo Can you also do it for the repository optaplanner-quickstarts?
> https://github.com/kiegroup/optaplanner-quickstarts

done https://github.com/kiegroup/optaplanner-quickstarts/pull/138

### CODE REVIEW

**Comment by Ginxo** [comment]
@rsynek @yurloc @ge0ffrey I'm not sure about how this movement affects to Jenkins. 
and what about `dsl/*` files? 
Can you please provide some information? thanks.

**Comment by radtriste** [comment]
`.ci/jenkins/dsl/jobs.groovy` content also need to be updated. I will provide you with a PR.
`(build) optaplanner` failing is totally normal as the current PR check cannot find the `Jenkinsfile` in the right path.

Also, I think this should be merged after https://github.com/kiegroup/optaplanner/pull/1398 that I am working on and hoping to merge before end of the week so we have more flexibility on PR checks

**Comment by radtriste** [comment]
created https://github.com/kiegroup/kogito-pipelines/pull/204 for the scanning of dsl folder

**Comment by yurloc** [comment]
> ERROR: /var/lib/jenkins/jobs/KIE/jobs/master/jobs/fdb/jobs/optaplanner-master.fdb/workspace@script/.ci/jenkins/Jenkinsfile.buildchain not found

I'm getting this in [optaplanner-master.fdb#7](https://eng-jenkins-csb-business-automation.apps.ocp4.prod.psi.redhat.com/job/KIE/job/master/job/fdb/job/optaplanner-master.fdb/7/console) in #1373.

That is a good thing, right? It means the job has been updated for the new Jenkinsfile location.

**Comment by Ginxo** [comment]
> > ERROR: /var/lib/jenkins/jobs/KIE/jobs/master/jobs/fdb/jobs/optaplanner-master.fdb/workspace@script/.ci/jenkins/Jenkinsfile.buildchain not found
> 
> I'm getting this in [optaplanner-master.fdb#7](https://eng-jenkins-csb-business-automation.apps.ocp4.prod.psi.redhat.com/job/KIE/job/master/job/fdb/job/optaplanner-master.fdb/7/console) in #1409.
> 
> That is a good thing, right? It means the job has been updated for the new Jenkinsfile location.

it is since https://github.com/kiegroup/kie-jenkins-scripts/pull/1025 was merged yesterday and https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1688 recently merged @yurloc

**Comment by radtriste** [comment]
jenkins rerun optaplanner tests

**Comment by radtriste** [comment]
@Ginxo Need also to update the path in the GHAction file for jenkins tests

**Review by ge0ffrey — APPROVED** [review]

**Comment by ge0ffrey** [comment]
Great stuff! Let's get this merged.
@Ginxo Can you also do it for the repository optaplanner-quickstarts?
https://github.com/kiegroup/optaplanner-quickstarts

**Comment by ge0ffrey** [comment]
@Ginxo @radtriste Feel free to merge this set of PR's when you guys think the timing is right so CI won't be disrupted too much.

**Review by rsynek — APPROVED** [review]

**Comment by radtriste** [comment]
@rsynek @Ginxo are we good to merge those ?

**Comment by Ginxo** [comment]
> @rsynek @Ginxo are we good to merge those ?

I would wait for https://github.com/kiegroup/optaplanner-quickstarts/pull/138 to be reviewed, wdyt?

**Comment by radtriste** [comment]
right ...

**Comment by ge0ffrey** [comment]
> > @rsynek @Ginxo are we good to merge those ?
> 
> I would wait for [kiegroup/optaplanner-quickstarts#138](https://github.com/kiegroup/optaplanner-quickstarts/pull/138) to be reviewed, wdyt?

That one got replaced by this one which is good to merge: https://github.com/kiegroup/optaplanner/pull/1414

Go for it :)

**Pull request merged**
