### PR TITLE
Bump Quarkus 2.0.1.Final

### PR DESCRIPTION
**Pull request by evacchi**
bundle:

- https://github.com/kiegroup/kogito-runtimes/pull/1422
- https://github.com/kiegroup/optaplanner/pull/1413
- https://github.com/kiegroup/optaplanner-quickstarts/pull/133

### CODE REVIEW

**Comment by rsynek** [comment]
Jenkins run fdb

**Comment by rsynek** [comment]
Jenkins run fdb

**Comment by yurloc** [comment]
**Linux - Full Downstream Build**

[ERROR] Failed to execute goal on project jbpm-wb-showcase: Could not resolve dependencies for project org.jbpm:jbpm-wb-showcase:war:7.57.0-SNAPSHOT: Failed to collect dependencies at org.apache.chemistry.opencmis:chemistry-opencmis-commons-impl:jar:0.11.0 -> com.sun.xml.ws:jaxws-rt:jar:2.1.7 -> com.sun.xml.stream.buffer:streambuffer:jar:0.9 -> org.jvnet.staxex:stax-ex:jar:RELEASE: Failed to read artifact descriptor for org.jvnet.staxex:stax-ex:jar:RELEASE: Failed to resolve version for org.jvnet.staxex:stax-ex:jar:RELEASE -> [Help 1]

**Comment by rsynek** [comment]
The FDB is irrelevant for OptaPlanner 8 (master branch) as it checks out optawebs/7.x, kie-server, kie-wb, etc.

The optawebs have been checked manually.

**Review by rsynek — APPROVED** [review]
Good to merge.

**Pull request merged**
