### PR TITLE
Remove migrated optaplanner-integration module

### PR DESCRIPTION
**Pull request by cuijulian**
Jira: https://issues.redhat.com/browse/PLANNER-1317

Merge together with: https://github.com/kiegroup/optaplanner-wb/pull/350

### CODE REVIEW

**Comment by cuijulian** [comment]
Jenkins execute full downstream build

**Comment by cuijulian** [comment]
Jenkins execute full downstream build

**Comment by ge0ffrey** [comment]
@cuijulian I am using the optaplanner-integration module to land the spring-boot work, so that parent module can't go. I 'll try to get the PR merged today.

**Comment by cuijulian** [comment]
@ge0ffrey Ok I'll wait for your PR. I made some comments in the [Jira](https://issues.redhat.com/browse/PLANNER-1317) and a [related one](https://issues.redhat.com/browse/PLANNER-989), could you take a look when you get a chance?

**Comment by ge0ffrey** [comment]
@cuijulian my PR merged, please adjust this one accordingly and I 'll merge :)

**Comment by cuijulian** [comment]
Jenkins execute full downstream build

**Comment by ge0ffrey** [comment]
full downstream build is green, except for some random failing jbpm tests

**Pull request merged**
