### PR TITLE
BXMSPROD-1265: Conscious language initiative

### PR DESCRIPTION
**Pull request by radtriste**
**PLEASE DO NOT MERGE. THIS WILL BE DONE WHEN `master` will be renamed as `main`**

Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/188
- https://github.com/kiegroup/kogito-runtimes/pull/1365
- https://github.com/kiegroup/optaplanner/pull/1372
- https://github.com/kiegroup/optaweb-employee-rostering/pull/660
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/532
- https://github.com/kiegroup/optaplanner-quickstarts/pull/144
- https://github.com/kiegroup/kogito-apps/pull/882
- https://github.com/kiegroup/kogito-examples/pull/729
- https://github.com/kiegroup/kogito-images/pull/516
- https://github.com/kiegroup/kogito-operator/pull/905
- https://github.com/kiegroup/rhpam-kogito-operator/pull/44

### CODE REVIEW

**Comment by radtriste** [comment]
Jenkins tests failing due to https://github.com/kiegroup/kogito-pipelines/pull/188 and `main` branch not yet existing on `kogito-pipelines`

**Comment by ge0ffrey** [comment]
@radtriste Thank you. Will both optaweb-* repos be done at a later time?

**Comment by radtriste** [comment]
@ge0ffrey Waiting for @mbiarnes to schedule the migration (that is why it is draft for now) but I guess optaweb-* will also be done

**Comment by ge0ffrey** [comment]
Thanks Tristan

**Review by rsynek — APPROVED** [review]

**Comment by rsynek** [comment]
Let's also add the quickstarts on the list:
https://github.com/kiegroup/optaplanner-quickstarts/search?q=master&type=code

**Comment by radtriste** [comment]
jenkins rerun optaplanner tests

**Comment by radtriste** [comment]
optaplanner check failing because optaplanner-quickstarts branch calculation is wrong due to current target branch `master` and check done against `main`

**Pull request merged**
