### PR TITLE
Fixing ArithmeticException

### PR DESCRIPTION
**Pull request by davidjmoon**
https://issues.jboss.org/browse/PLANNER-1347?_sscc=t

### CODE REVIEW

**Comment by kie-ci7** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by davidjmoon** [comment]
ok to test!

**Comment by ge0ffrey** [comment]
ok to test

**Comment by ge0ffrey** [comment]
Thanks David!

**Comment by davidjmoon** [comment]
No problem!  Do you have a date for when this fix will be released in Maven?

**Pull request merged**
