### PR TITLE
PLANNER-2363 Re-enable the turtle tests job

### PR DESCRIPTION
**Pull request by rsynek**
### JIRA
https://issues.redhat.com/browse/PLANNER-2363

### Checklist
- [ ] Documentation updated if applicable.
- [ ] Upgrade recipe provided if applicable.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>full downstream build</b> please add comment: <b>Jenkins run fdb</b>
* for a <b>compile downstream build</b> please add comment: <b>Jenkins run cdb</b>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* for an <b>upstream build</b> please add comment: <b>Jenkins run upstream</b>
* for a <b>Quarkus LTS check</b> please add comment: <b>Jenkins run LTS</b>
</details>

### CODE REVIEW

**Review by triceo — APPROVED** [review]
Good work!
Let's see the test job finish before merging.

**Comment by rsynek** [comment]
Generating the job that starts the pipeline is still in progress.

**Review by radtriste — APPROVED** [review]
one minor comment

**Comment by rsynek** [comment]
@radtriste the job has been successfully created at [1]. Would you kindly review the latest changes?

[1] https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/rsynek/job/kogitoTest/job/other/

**Review by radtriste — APPROVED** [review]

**Comment by rsynek** [comment]
Ready to merge once the test job finishes.

**Pull request merged**
