### PR TITLE
Removing casting

### PR DESCRIPTION
**Pull request by Hassan-Elseoudy**
### Updates

Currently, This project has **+9K** of warnings and code smells.

<a href="https://ibb.co/NpRxdTN">image</a>

I'm starting to work on those warnings, If acceptable, and waiting for your review to start.

### Checklist
- [ ] Documentation updated if applicable.
- [ ] Upgrade recipe provided if applicable.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>full downstream build</b> please add comment: <b>Jenkins run fdb</b>
* for a <b>compile downstream build</b> please add comment: <b>Jenkins run cdb</b>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* for an <b>upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by ge0ffrey** [comment]
ok to test

**Comment by ge0ffrey** [comment]
@ Hassan-Elseoudy Good idea to clean these up - we have done actions like that in the past.
Do note to make these changes quickly and successfully merged, I recommend making separate PR's for different types of code smell fixes. Some kind of code smell fixes will be controversial and might block the entire PR it is contained of being merged quickly. More, smaller PR's (like in it's current state) are perfect. But doing many changes for the same code smell type is fine too.

In it's current state (if it wasn't a draft) I 'd merge this PR.

**Comment by Hassan-Elseoudy** [comment]
Okay You can merge this and I'll open new pull request for each category soon. (If you want)
@ge0ffrey

**Comment by ge0ffrey** [comment]
Thanks @Hassan-Elseoudy !

**Pull request merged**
