### PR TITLE
PLANNER-2444 reproducer

### PR DESCRIPTION
**Pull request by rsynek**
A reproducer for https://issues.redhat.com/browse/PLANNER-2444; do not merge.

### Checklist
- [ ] Documentation updated if applicable.
- [ ] Upgrade recipe provided if applicable.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>specific pull request build</b> please add comment: <b>Jenkins (re)run [optaplanner|apps|examples] tests</b>
* for a <b>full downstream build</b> please add comment: <b>Jenkins run fdb</b>
* for a <b>compile downstream build</b> please add comment: <b>Jenkins run cdb</b>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* for an <b>upstream build</b> please add comment: <b>Jenkins run upstream</b>
* for a <b>Quarkus LTS check</b> please add comment: <b>Jenkins run LTS</b>
* for a <b>specific Quarkus LTS check</b> please add comment: <b>Jenkins (re)run [optaplanner|apps|examples] LTS</b>
* for a <b>Native check</b> please add comment: <b>Jenkins run native</b>
* for a <b>specific Native LTS check</b> please add comment: <b>Jenkins (re)run [optaplanner|apps|examples] native</b>
</details>

### CODE REVIEW

**Comment by Christopher-Chianelli** [comment]
Verified; investigating

**Comment by Christopher-Chianelli** [comment]
Not related to GIZMO; this reproduces with `overrideConfigKey("quarkus.optaplanner.solver.domain-access-type", "REFLECTION")` (which does not transform/generate any classes)

**Comment by Christopher-Chianelli** [comment]
@rsynek isolated the issue. This issue is in all Quarkus projects; getDeclaredMethods contract is violated; it returns super classes methods too (although their declaring class is wrong)

**Comment by Christopher-Chianelli** [comment]
Quarkus issue (w/ isolated reproducer that only uses arc): https://github.com/quarkusio/quarkus/issues/17809

**Comment by Christopher-Chianelli** [comment]
@rsynek FYI, the issue in `optaplanner-core`; an additional `getId` bridge method is generated, and OptaPlanner does not ignore bridge or synthetic methods when doing annotation lookups

**Comment by triceo** [comment]
Merged in https://github.com/kiegroup/optaplanner/pull/1377

**Pull request closed without merging**
