### PR TITLE
Modularization chapter one

### PR DESCRIPTION
**Pull request by gsheldon**
Hi Geoffrey,

I have created the modular files for Chapter One. However, while the book builds, there is a level Warning that comes up and the subsections are not appearing in the TOC. I'm not sure why this is happening. I'm submitting this to you so you can take a look and see if we can figure out how to address this.

Thanks,

Gemma.

### CODE REVIEW

**Comment by ge0ffrey** [comment]
Can I presume there are no other changes here except than splitting up the file?

**Comment by gsheldon** [comment]
Yes, correct. I've just split up the exact same file we had, no other changes at all :)

**Comment by ge0ffrey** [comment]
I am merging this manually and reviewing/adjusting it further locally.

1) I get these warnings during "mvn clean install" of "optaplanner-docs"
```
[INFO] --- asciidoctor-maven-plugin:1.5.3:process-asciidoc (generate-single-html) @ optaplanner-docs ---
asciidoctor: WARNING: Chapter-Planner_introduction/Section-whatIsOptaPlanner.adoc: line 2: section title out of sequence: expected level 2, got level 4
asciidoctor: WARNING: Chapter-Planner_introduction/Section-whatIsAPlanningProblem.adoc: line 2: section title out of sequence: expected level 2, got level 4
asciidoctor: WARNING: Chapter-Planner_introduction/Section-requirements.adoc: line 2: section title out of sequence: expected level 2, got level 4
asciidoctor: WARNING: Chapter-Planner_introduction/Section-governance.adoc: line 2: section title out of sequence: expected level 2, got level 4
asciidoctor: WARNING: Chapter-Planner_introduction/Section-downloadandruntheexamples.adoc: line 2: section title out of sequence: expected level 2, got level 4
[INFO] Rendered /home/ge0ffrey/projects/jboss/just-optaplanner/optaplanner/optaplanner-docs/src/main/asciidoc/index.adoc
```

The cause is clear: the sections start with "==" but their included as "leveloffset=+2". I'll fix.

2) The naming of the files is an insconsitent mess:

* Section-downloadandruntheexamples.adoc uses no case
* Section-whatIsAPlanningProblem.adoc uses camel case
* All existing chapter files use this convention: Chapter-Planner_introduction.adoc

I'll fix, probably for now do it the existing way, although going to a denser format (camelcase, drop "Chapter" prefix etc) is probably desirable.

**Comment by ge0ffrey** [comment]
Merged manually, see https://github.com/kiegroup/optaplanner/tree/master/optaplanner-docs/src/main/asciidoc/Chapter-Planner_introduction

**Pull request closed without merging**
