### PR TITLE
PLANNER-1716 Switch OptaPlanner to junit-vintage-engine

### PR DESCRIPTION
**Pull request by rsynek**
Depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1116

### CODE REVIEW

**Comment by rsynek** [comment]
jenkins retest this

**Comment by ge0ffrey** [comment]
@rsynek optaplanner-test currently grabs in junit 4 at comile time because it imports org.junit.Assert.* . That's should remain as-is indeed: but in 8.0, we'll want to change that to junit 5. I 'll add it to the 8.0 jira todo list.

**Comment by rsynek** [comment]
@yurloc yes, it should be possible to start using JUnit 5 features in the code base - of course first we need to add some other dependencies, e.g. junit-jupiter-api.

**Comment by triceo** [comment]
Correct. `vintage` is just the v4 APIs implemented with v5 backend. Jupiter is the v5 API over the v5 backend.

**Comment by mareknovotny** [comment]
Shouldn't you start open discussion for other teams to suggest other teams to start use this one step ahead?
As now with this PR we will have in kiegroup different junit and only Optaplanner will use vintage module

**Comment by rsynek** [comment]
@mareknovotny +1 for discussing it with the entire group. I tried to do the switch in kie-parent, but all tests based on https://github.com/kiegroup/lienzo-tests/blob/master/src/main/java/com/ait/lienzo/test/LienzoMockitoTestRunner.java fail due to a classloading issue.

**Comment by ge0ffrey** [comment]
Merged these PR's, but that discussion with the entire group should start in parallel @rsynek - Ideally the drools and droolsjbpm-integration repository also switch to the new engine sooner rather than later.

**Pull request merged**
