### PR TITLE
Remove non-inclusive word master from twitterbootstap

### PR DESCRIPTION
**Pull request by dupliaka**
### JIRA

See the  https://issues.redhat.com/browse/BAPL-1990 initiative

### Checklist
- [ ] Documentation updated if applicable.
- [ ] Upgrade recipe provided if applicable.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

We do "simple" maven builds, they are just basically maven commands, but just because we have multiple repositories related between them and one change could affect several of those projects by multiple pull requests, we use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.

[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is not only a github-action tool but a CLI one, so in case you posted multiple pull requests related with this change you can easily reproduce the same build by executing it locally. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>specific pull request build</b> please add comment: <b>Jenkins (re)run [optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] tests</b>
* for a <b>full downstream build</b> 
  * for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  * for <b>github actions</b> job: add the label `run_fdb`
* for a <b>compile downstream build</b> please add comment: <b>Jenkins run cdb</b>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* for an <b>upstream build</b> please add comment: <b>Jenkins run upstream</b>
* for a <b>Quarkus LTS check</b> please add comment: <b>Jenkins run LTS</b>
* for a <b>specific Quarkus LTS check</b> please add comment: <b>Jenkins (re)run [optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] LTS</b>
* for a <b>Native check</b> please add comment: <b>Jenkins run native</b>
* for a <b>specific Native LTS check</b> please add comment: <b>Jenkins (re)run [optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] native</b>
</details>

### CODE REVIEW

**Review by yurloc — CHANGES_REQUESTED** [review]
Maybe we should finally get rid of the JS libraries committed in the Git history (https://issues.redhat.com/browse/PLANNER-439).

@dupliaka if this is necessary in order to verify BAPL-1990 then I think you should target the corresponding release branch, right? If that's the case, please open a new PR and let's close this and do PLANNER-439 instead (I can do that).

**Comment by triceo** [comment]
I agree, I'd much rather see bootstrap removed than manually fixed.
It's not just these words that may offend someone, it is also all the fixes we are not getting by having a years-old copy of the code directly in the repo.

**Comment by dupliaka** [comment]
Yes, agree. The current version is 5.x and we are using 2.x

**Comment by ge0ffrey** [comment]
Agreed, we shouldn't modify these files, only upgrade them - or indeed, better yet, replace them with a webjar dependency, just like the optaplanner-quickstarts.

**Comment by ge0ffrey** [comment]
optaplanner-benchmark should depend on 

```
    <dependency>
      <groupId>org.webjars</groupId>
      <artifactId>bootstrap</artifactId>
      <version>???</version>
      <scope>runtime</scope>
    </dependency>
```
so we can remove that code.

This of course increases the scope of this issue. @dupliaka Are you interested in pursing this increased-scope issue?

**Comment by triceo** [comment]
One thing to note, though: fixing this by upgrading and removing Bootstrap will be a large project. Not something we can get done really quickly.

**Comment by ge0ffrey** [comment]
> One thing to note, though: fixing this by upgrading and removing Bootstrap will be a large project. Not something we can get done really quickly.

I am hoping it's relatively doable. If we add the webjar dependency to the pom.xml, it's just a matter of changing the path were those files are copied from, by `WebsiteResourceUtils.java` - and of course deleting the files.

**Comment by dupliaka** [comment]
@ge0ffrey unfortunately I was not able to do that in 30 minutes - the bootstrap files do not maps on those we use, so better to complete this as a part of an issue. 
I propose to make a smaller change for 8.11.x so that could be verified for 7.12 CR2 and assign https://issues.redhat.com/browse/PLANNER-439 to me if @yurloc do not mind

**Comment by yurloc** [comment]
@dupliaka Thanks for volunteering. I have removed the `deferred` label from https://issues.redhat.com/browse/PLANNER-439 and assigned it to you. It's now in the backlog.

Closing this. Anna, feel free to backport this PR to `8.11.x` if that's required for 7.12.

**Pull request closed without merging**
