### PR TITLE
BXMSPROD-883 pull request flow on github actions

### PR DESCRIPTION
**Pull request by Ginxo**
https://issues.redhat.com/browse/BXMSPROD-883

### CODE REVIEW

**Comment by triceo** [comment]
Please rebase to latest master, @Ginxo . The error will go away.

Also, would you mind explaining what is the intention here? What are you trying to accomplish?
Updating the JIRA description would be enough, so that everyone can read the same information there.

**Comment by triceo** [comment]
Would you mind explaining what is the intention here? What are you trying to accomplish?
Updating the JIRA description would be enough, so that everyone can read the same information there.

**Comment by triceo** [comment]
Also, if you rebase on latest 7.x branch, the Revapi failures should go away.
(We've recently committed a fix for Revapi to compare against 7.39.)

**Comment by Ginxo** [comment]
@triceo https://issues.redhat.com/browse/BXMSPROD-883 description updated.

**Comment by triceo** [comment]
Depends on https://github.com/kiegroup/optaplanner/pull/858 to fix the build.

**Comment by Ginxo** [comment]
@ge0ffrey branch mapping mechanism added to https://github.com/kiegroup/github-action-build-chain
thanks to this we can specify dependencies like `drools@7.x:master` or `optaplanner@master:7.x`

**Comment by triceo** [comment]
@Ginxo Geoffrey is gone for a 3-week PTO. If you want this merged sooner than that, I'm your guy.
So far, it looks good. I'll just wait for the PR to turn green. Is there anything else you intend to do with this PR?

**Comment by Ginxo** [comment]
thanks @triceo, just informing @ge0ffrey whenever he is available. All the PR from https://issues.redhat.com/browse/BXMSPROD-883 should be merged in a row, I would ask you to add your review here, please. Thanks.

**Comment by triceo** [comment]
@Ginxo I don't see the Github Actions run - do we need to do anything to make it execute?
Also, do you intend to do anything about master as well?

**Comment by Ginxo** [comment]
@triceo the event is `workflow_dispatch` which means https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch so it shouldn't be triggered (not automatically). It should be assigned to `pull_request` but I don't want to enable it until opta team agrees. So this flow is just used by [kiegroup/github-action-build-chain](kiegroup/github-action-build-chain) in order to keep building the chain for the rest of RHBA projects.
About master, up to you, I plan to also discuss it with you (opta team & @ge0ffrey ) once the PR flow is stable enough.

**Pull request merged**
