### PR TITLE
Remove unnecessary mvel dependency to avoid version conflict

### PR DESCRIPTION
**Pull request by dupliaka**
### JIRA

https://issues.redhat.com/browse/PLANNER-2149

### Referenced pull requests

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>full downstream build</b> please add comment: <b>Jenkins run fdb</b>
* for a <b>compile downstream build</b> please add comment: <b>Jenkins run cdb</b>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* for an <b>upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by rsynek** [comment]
@triceo It seems we don't need to declare the `mvel` dependency on the `7.x` branch. Adding you as a reviewer just in case I am missing something.

**Review by rsynek — APPROVED** [review]

**Review by triceo — APPROVED** [review]
Testing this will be tricky, though.
Please make sure both Optawebs work, and that Quarkus quickstarts function properly too.

**Comment by dupliaka** [comment]
> Testing this will be tricky, though.
> Please make sure both Optawebs work, and that Quarkus quickstarts function properly too.

Ok I will check baselines manually and nighties will go for the rest

**Comment by dupliaka** [comment]
> Testing this will be tricky, though.
> Please make sure both Optawebs work, and that Quarkus quickstarts function properly too.

I check VRP and ERP are find. Though it is unclear how to check quickstarts since this change is for 7.x and though we do not have this problem in quickstarts. However I am afraid to miss a spring boot timetable which we supply as a reference implementation. @triceo could you please advice me on that?

**Comment by triceo** [comment]
The quickstarts for 7.x are directly on the branch here, @dupliaka :
https://github.com/kiegroup/optaplanner/tree/7.x/optaplanner-quickstarts/spring-boot-school-timetabling

**Comment by dupliaka** [comment]
> The quickstarts for 7.x are directly on the branch here, @dupliaka :
> https://github.com/kiegroup/optaplanner/tree/7.x/optaplanner-quickstarts/spring-boot-school-timetabling

Indeed, I was blind, sorry

**Comment by dupliaka** [comment]
Removed completely ooptaplanner-quarkus-integration/optaplanner-quarkus/runtime/pom.xml

**Pull request closed without merging**
