### PR TITLE
Change maven.compiler.release from 11 to 8.

### PR DESCRIPTION
**Pull request by ge0ffrey**

### CODE REVIEW

**Review by Christopher-Chianelli — APPROVED** [review]

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by ge0ffrey** [comment]
Linux builds are failing again:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0-jboss-2:compile (default-compile) on project optaplanner-core: Compilation failure: Compilation failure: 

[ERROR] /home/jenkins/workspace/KIE/kogito/ghprb-webhooks/optaplanner/optaplanner/optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/rules/TriGroupBy1Map1CollectFastMutator.java:[21,1] cannot find symbol
```

**Comment by triceo** [comment]
That failure makes no sense. `groupBy` has been in Drools for months.

**Comment by ge0ffrey** [comment]
The Linux failure is unrelated, someone or something corrupted the kogito-drools snapshots to use drools 7.41 instead of 7.46+

**Pull request merged**
