### PR TITLE
[7.44.x] PLANNER-2085 Missing directory in optaplanner distribution zipped archives

### PR DESCRIPTION
**Pull request by rsynek**
A cherry-pick of https://github.com/kiegroup/optaplanner/pull/986.

### JIRA
https://issues.redhat.com/browse/PLANNER-2085

### Checklist
- [x] Documentation updated if applicable.
- [x] Upgrade recipe provided if applicable.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>full downstream build</b> please add comment: <b>Jenkins run fdb</b>
* for a <b>compile downstream build</b> please add comment: <b>Jenkins run cdb</b>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* for an <b>upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by dupliaka — APPROVED** [review]

**Comment by rsynek** [comment]
ad Build Chain: "The builder requested using id = smart cannot be found" - The Build Chain itself appears to be broken.
ad "Linux": please ignore it; the jenkinsfile was not back-ported to this branch, but the wrapper job still reacts to this PR.

**Review by ge0ffrey — APPROVED** [review]

**Comment by ge0ffrey** [comment]
@rsynek If 7.44 is broken without this fix, and the CI is a false negative, and the tag is coming soon, then I don't mind if you merge this blind, worst case scenario.

**Comment by rsynek** [comment]
@Ginxo could you please advise if there is a quick fix to the Build Chain on this branch? I think I have seen similar issue on the 7.x branch in the past.

**Comment by rsynek** [comment]
@ge0ffrey let me make one thing clear: we are not merging blindly. The "Linux - Pull Request" is the PR check we've had for years (and for years it was the only PR check) and this one is green.

**Pull request merged**
