### PR TITLE
Remove dependency to jcommon and fix code due to JFreeChart upgrade 

### PR DESCRIPTION
**Pull request by FredPraca**
Requires: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1077

### CODE REVIEW

**Comment by kie-ci9** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by ge0ffrey** [comment]
ok to test

**Comment by ge0ffrey** [comment]
Before we can merge, isn't there a linked PR for the kie-parent pom that upgrades the jfreechart and removes the jcommons version?

**Comment by FredPraca** [comment]
> 
> 
> Before we can merge, isn't there a linked PR for the kie-parent pom that upgrades the jfreechart and removes the jcommons version?
> 
> https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/master/pom.xml#L276

Yes, I tried to make it the good way :)
[Here it is](https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1077)

**Comment by ge0ffrey** [comment]
@FredPraca github's search in organization functionality can help with that:
  https://github.com/search?q=org%3Akiegroup+jfreechart&type=Code

**Comment by ge0ffrey** [comment]
@FredPraca Thanks, nice work! The new graphs look a bit glossier (=prettier) and getting rid of the jfree commons jar dependency is very welcome.

If you want your name in the contributors list on optaplanner.org -> team, send a PR for https://github.com/kiegroup/optaplanner-website/blob/master/_config/users.yml

**Comment by FredPraca** [comment]
It was an easy task :)
Moreover I needed this upgrade as my project already imported 1.5.0 as dependency :)

**Pull request merged**
