### PR TITLE
KOGITO-5480 Reorganized seed jobs & trigger automatically

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/KOGITO-5480

Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/206
- https://github.com/kiegroup/kogito-runtimes/pull/1429
- https://github.com/kiegroup/optaplanner/pull/1416
- https://github.com/kiegroup/kogito-apps/pull/928
- https://github.com/kiegroup/kogito-examples/pull/778
- https://github.com/kiegroup/kogito-images/pull/575
- https://github.com/kiegroup/kogito-operator/pull/929
- https://github.com/kiegroup/rhpam-kogito-operator/pull/53

### Checklist
- [ ] Documentation updated if applicable.
- [ ] Upgrade recipe provided if applicable.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>specific pull request build</b> please add comment: <b>Jenkins (re)run [optaplanner|apps|examples] tests</b>
* for a <b>full downstream build</b> please add comment: <b>Jenkins run fdb</b>
* for a <b>compile downstream build</b> please add comment: <b>Jenkins run cdb</b>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* for an <b>upstream build</b> please add comment: <b>Jenkins run upstream</b>
* for a <b>Quarkus LTS check</b> please add comment: <b>Jenkins run LTS</b>
* for a <b>specific Quarkus LTS check</b> please add comment: <b>Jenkins (re)run [optaplanner|apps|examples] LTS</b>
* for a <b>Native check</b> please add comment: <b>Jenkins run native</b>
* for a <b>specific Native LTS check</b> please add comment: <b>Jenkins (re)run [optaplanner|apps|examples] native</b>
</details>

### CODE REVIEW

**Review by Ginxo — APPROVED** [review]
LGTM

**Comment by triceo** [comment]
Needs to be synced with https://github.com/kiegroup/optaplanner/pull/1414.

**Comment by radtriste** [comment]
@triceo no need to sync this PR with https://github.com/kiegroup/optaplanner/pull/1414, they are quite independent as themselves.
Only https://github.com/kiegroup/kogito-pipelines/pull/206 should be sync with https://github.com/kiegroup/optaplanner/pull/1414 but anyway I plan to merge the pipelines one after the PR from Enrique ;)

THis one can be merged with no harm on anything as it is just adding a file which will be used later by https://github.com/kiegroup/kogito-pipelines/pull/206 ;)

**Comment by radtriste** [comment]
@rsynek FYI
This will allow to have automatic refresh of Kogito jobs once update is done to path `.ci/jenkins/`
The given Jenkinsfile.seed will be launched when that happens and it then uses this [file](https://github.com/kiegroup/kogito-pipelines/pull/206/files?file-filters%5B%5D=.groovy&file-filters%5B%5D=.md&file-filters%5B%5D=.seed&file-filters%5B%5D=.xml&file-filters%5B%5D=.yaml#diff-d510fe6e71d1570ad236d12721ddfa1dcbfaaf285f83fdaf0d2127ab3b2718b1) to execute the different step of job re-generation

**Comment by radtriste** [comment]
More info in the description of this PR: https://github.com/kiegroup/kogito-pipelines/pull/206

**Comment by radtriste** [comment]
(nothing directly related to buildchain though, this is pure Jenkins DSL job generation related)

**Comment by radtriste** [comment]
`apps` is having problems of timeout. I opened a conversation on Zulip: https://kie.zulipchat.com/#narrow/stream/232676-kogito/topic/.60testProcessInstanceIndex.60.20tests.20fail.20often.20on.20Jenkins
I guess if you are good, then we can merge this one

**Pull request merged**
