### PR TITLE
[7.67.x-blue][BXMSPROD-2057] Updating references to the new kie-ci actions folder

### PR DESCRIPTION
**Pull request by bacciotti**

### CODE REVIEW

**Review by Ginxo — APPROVED** [review]
LGTM

**Comment by lampajr** [comment]
I would close this one as not needed because optaplanner is no more include in `7.67.x-blue`, right @mareknovotny @Ginxo ?

**Comment by bacciotti** [comment]
Closing this as we do not need it for now.

**Comment by mareknovotny** [comment]
blue branches are excluded in case of optaplanner/optawebs

**Pull request closed without merging**
