### PR TITLE
excluded dependency to prevent enforcer rule failures

### PR DESCRIPTION
**Pull request by mbiarnes**
### Referenced pull requests

https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1622
https://github.com/kiegroup/optaplanner/pull/1264

### Checklist
- [ ] Documentation updated if applicable.
- [ ] Upgrade recipe provided if applicable.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>full downstream build</b> please add comment: <b>Jenkins run fdb</b>
* for a <b>compile downstream build</b> please add comment: <b>Jenkins run cdb</b>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* for an <b>upstream build</b> please add comment: <b>Jenkins run upstream</b>
* for a <b>Quarkus LTS check</b> please add comment: <b>Jenkins run LTS</b>
* for a <b>Native check</b> please add comment: <b>Jenkins run native</b>
</details>

### CODE REVIEW

**Review by mareknovotny — APPROVED** [review]

**Review by triceo — APPROVED** [review]
Don't see why not.

**Review by rsynek — APPROVED** [review]

**Review by ge0ffrey — APPROVED** [review]
LGTM, but some questions:
- Why is Hibernate still not using Jakarta EE dependencies?
- Are we using the latest version of Hibernate? Or at least the same version as WildFly 23 / Quarkus 1.13? If not, let's fix that first, maybe this fixes itself?

If those all don't fix it, this is a good change

**Review by yurloc — APPROVED** [review]
LGTM.

**Comment by triceo** [comment]
Closing as WF23 alignment was merged earlier this week in a different PR.

**Pull request closed without merging**
