### PR TITLE
[KOGITO-6236] Introducing Capability definition for OptaPlanner extensions

### PR DESCRIPTION
**Pull request by danielezonca**
### JIRA

https://issues.redhat.com/browse/KOGITO-6236

### Referenced pull requests

- https://github.com/kiegroup/kogito-runtimes/pull/1703
- https://github.com/kiegroup/optaplanner/pull/1662

### Checklist
- [ ] Documentation updated if applicable.
- [ ] Upgrade recipe provided if applicable.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

We do "simple" maven builds, they are just basically maven commands, but just because we have multiple repositories related between them and one change could affect several of those projects by multiple pull requests, we use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.

[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is not only a github-action tool but a CLI one, so in case you posted multiple pull requests related with this change you can easily reproduce the same build by executing it locally. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>specific pull request build</b> please add comment: <b>Jenkins (re)run [optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] tests</b>
* for a <b>full downstream build</b> 
  * for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  * for <b>github actions</b> job: add the label `run_fdb`
* for a <b>compile downstream build</b> please add comment: <b>Jenkins run cdb</b>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* for an <b>upstream build</b> please add comment: <b>Jenkins run upstream</b>
* for a <b>Quarkus LTS check</b> please add comment: <b>Jenkins run LTS</b>
* for a <b>specific Quarkus LTS check</b> please add comment: <b>Jenkins (re)run [optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] LTS</b>
* for a <b>Native check</b> please add comment: <b>Jenkins run native</b>
* for a <b>specific Native LTS check</b> please add comment: <b>Jenkins (re)run [optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] native</b>
</details>

### CODE REVIEW

**Comment by rsynek** [comment]
@danielezonca The `kogito-examples` check is failing; I suspect there is yet another place where we need to disable REST generation:
https://github.com/kiegroup/kogito-examples/tree/stable/process-optaplanner-quarkus

**Comment by rsynek** [comment]
> @danielezonca The `kogito-examples` check is failing; I suspect there is yet another place where we need to disable REST generation: https://github.com/kiegroup/kogito-examples/tree/stable/process-optaplanner-quarkus

@danielezonca or maybe not; I have seen the same failure on my PR and now it's gone. I cannot reproduce it locally.

**Review by rsynek — APPROVED** [review]

**Comment by rsynek** [comment]
Jenkins rerun kogito-examples tests

**Comment by danielezonca** [comment]
> > @danielezonca The `kogito-examples` check is failing; I suspect there is yet another place where we need to disable REST generation: https://github.com/kiegroup/kogito-examples/tree/stable/process-optaplanner-quarkus
> 
> @danielezonca or maybe not; I have seen the same failure on my PR and now it's gone. I cannot reproduce it locally.

I think a build started without including latest changes from this PR so now there should be no error.
Btw I'm going to push an alternative approach that can make this PR not necessary anymore, let me see.

**Comment by danielezonca** [comment]
@rsynek 
Can you please review again?

**Review by rsynek — APPROVED** [review]

**Comment by danielezonca** [comment]
Jenkins run kogito-examples

**Comment by danielezonca** [comment]
Jenkins run kogito-examples tests

**Review by ge0ffrey — APPROVED** [review]

**Pull request merged**
