### PR TITLE
Fixed broken external links

### PR DESCRIPTION
**Pull request by FredPraca**
Fixed links to Late Acceptance and Step Counting Hill Climbing which were broken

### CODE REVIEW

**Comment by kie-ci7** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by mareknovotny** [comment]
ok to test

**Comment by ge0ffrey** [comment]
Thanks Frédéric !

**Comment by FredPraca** [comment]
You're welcome

**Pull request merged**
