### PR TITLE
PLANNER-2588: Add integration test for optaplanner-quarkus-benchmark

### PR DESCRIPTION
**Pull request by Christopher-Chianelli**
Native test fails due to AWT:

```
Error: Classes that should be initialized at run time got initialized during image building:
 sun.font.AttributeValues the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.font.AttributeValues got initialized use --trace-class-initialization=sun.font.AttributeValues
sun.java2d.SunGraphicsEnvironment the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.java2d.SunGraphicsEnvironment got initialized use --trace-class-initialization=sun.java2d.SunGraphicsEnvironment
sun.awt.SunHints the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.awt.SunHints got initialized use --trace-class-initialization=sun.awt.SunHints
java.awt.Font the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why java.awt.Font got initialized use --trace-class-initialization=java.awt.Font
sun.awt.X11.XToolkit the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.awt.X11.XToolkit got initialized use --trace-class-initialization=sun.awt.X11.XToolkit
sun.awt.HeadlessToolkit the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.awt.HeadlessToolkit got initialized use --trace-class-initialization=sun.awt.HeadlessToolkit
sun.awt.AWTAccessor the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.awt.AWTAccessor got initialized use --trace-class-initialization=sun.awt.AWTAccessor
sun.awt.SunToolkit the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.awt.SunToolkit got initialized use --trace-class-initialization=sun.awt.SunToolkit
java.awt.Component the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why java.awt.Component got initialized use --trace-class-initialization=java.awt.Component
sun.awt.util.PerformanceLogger the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.awt.util.PerformanceLogger got initialized use --trace-class-initialization=sun.awt.util.PerformanceLogger
java.awt.Toolkit the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why java.awt.Toolkit got initialized use --trace-class-initialization=java.awt.Toolkit
java.awt.Color the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why java.awt.Color got initialized use --trace-class-initialization=java.awt.Color
sun.awt.X11GraphicsEnvironment the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.awt.X11GraphicsEnvironment got initialized use --trace-class-initialization=sun.awt.X11GraphicsEnvironment
sun.font.EAttribute the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.font.EAttribute got initialized use --trace-class-initialization=sun.font.EAttribute
java.awt.Toolkit$DesktopPropertyChangeSupport the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why java.awt.Toolkit$DesktopPropertyChangeSupport got initialized use --trace-class-initialization=java.awt.Toolkit$DesktopPropertyChangeSupport
java.awt.GraphicsEnvironment$LocalGE the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why java.awt.GraphicsEnvironment$LocalGE got initialized use --trace-class-initialization=java.awt.GraphicsEnvironment$LocalGE
sun.awt.SunDisplayChanger the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.awt.SunDisplayChanger got initialized use --trace-class-initialization=sun.awt.SunDisplayChanger
sun.awt.UNIXToolkit the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.awt.UNIXToolkit got initialized use --trace-class-initialization=sun.awt.UNIXToolkit
java.awt.RenderingHints the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why java.awt.RenderingHints got initialized use --trace-class-initialization=java.awt.RenderingHints

com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 sun.font.AttributeValues the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.font.AttributeValues got initialized use --trace-class-initialization=sun.font.AttributeValues
sun.java2d.SunGraphicsEnvironment the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.java2d.SunGraphicsEnvironment got initialized use --trace-class-initialization=sun.java2d.SunGraphicsEnvironment
sun.awt.SunHints the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.awt.SunHints got initialized use --trace-class-initialization=sun.awt.SunHints
java.awt.Font the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why java.awt.Font got initialized use --trace-class-initialization=java.awt.Font
sun.awt.X11.XToolkit the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.awt.X11.XToolkit got initialized use --trace-class-initialization=sun.awt.X11.XToolkit
sun.awt.HeadlessToolkit the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.awt.HeadlessToolkit got initialized use --trace-class-initialization=sun.awt.HeadlessToolkit
sun.awt.AWTAccessor the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.awt.AWTAccessor got initialized use --trace-class-initialization=sun.awt.AWTAccessor
sun.awt.SunToolkit the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.awt.SunToolkit got initialized use --trace-class-initialization=sun.awt.SunToolkit
java.awt.Component the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why java.awt.Component got initialized use --trace-class-initialization=java.awt.Component
sun.awt.util.PerformanceLogger the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.awt.util.PerformanceLogger got initialized use --trace-class-initialization=sun.awt.util.PerformanceLogger
java.awt.Toolkit the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why java.awt.Toolkit got initialized use --trace-class-initialization=java.awt.Toolkit
java.awt.Color the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why java.awt.Color got initialized use --trace-class-initialization=java.awt.Color
sun.awt.X11GraphicsEnvironment the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.awt.X11GraphicsEnvironment got initialized use --trace-class-initialization=sun.awt.X11GraphicsEnvironment
sun.font.EAttribute the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.font.EAttribute got initialized use --trace-class-initialization=sun.font.EAttribute
java.awt.Toolkit$DesktopPropertyChangeSupport the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why java.awt.Toolkit$DesktopPropertyChangeSupport got initialized use --trace-class-initialization=java.awt.Toolkit$DesktopPropertyChangeSupport
java.awt.GraphicsEnvironment$LocalGE the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why java.awt.GraphicsEnvironment$LocalGE got initialized use --trace-class-initialization=java.awt.GraphicsEnvironment$LocalGE
sun.awt.SunDisplayChanger the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.awt.SunDisplayChanger got initialized use --trace-class-initialization=sun.awt.SunDisplayChanger
sun.awt.UNIXToolkit the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.awt.UNIXToolkit got initialized use --trace-class-initialization=sun.awt.UNIXToolkit
java.awt.RenderingHints the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why java.awt.RenderingHints got initialized use --trace-class-initialization=java.awt.RenderingHints
```

### JIRA

https://issues.redhat.com/browse/PLANNER-2588

### Checklist
- [ ] Documentation updated if applicable.
- [ ] Upgrade recipe provided if applicable.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

We do "simple" maven builds, they are just basically maven commands, but just because we have multiple repositories related between them and one change could affect several of those projects by multiple pull requests, we use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.

[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is not only a github-action tool but a CLI one, so in case you posted multiple pull requests related with this change you can easily reproduce the same build by executing it locally. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>specific pull request build</b> please add comment: <b>Jenkins (re)run [optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] tests</b>
* for a <b>full downstream build</b> 
  * for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  * for <b>github actions</b> job: add the label `run_fdb`
* for a <b>compile downstream build</b> please add comment: <b>Jenkins run cdb</b>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* for an <b>upstream build</b> please add comment: <b>Jenkins run upstream</b>
* for a <b>Quarkus LTS check</b> please add comment: <b>Jenkins run LTS</b>
* for a <b>specific Quarkus LTS check</b> please add comment: <b>Jenkins (re)run [optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] LTS</b>
* for a <b>Native check</b> please add comment: <b>Jenkins run native</b>
* for a <b>specific Native LTS check</b> please add comment: <b>Jenkins (re)run [optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] native</b>
</details>

### CODE REVIEW

**Comment by Christopher-Chianelli** [comment]
Note: reusing the TerminationRuntimeConfig from the `optaplanner` Quarkus extension in `optaplanner-benchmark` means the property description will be the same across both implementations. The alternative is code duplication, but then it easy to update one and not the other.

**Review by triceo — APPROVED** [review]

**Comment by triceo** [comment]
Jenkins execute native tests

**Comment by triceo** [comment]
Jenkins run native tests

**Comment by triceo** [comment]
The current failure is the same one we're seeing in Quarkus native CI upstream, and the one we are currently discussing on Zulip.
We need to wait for a fix.

**Comment by Christopher-Chianelli** [comment]
Native test still failing due to AWT; I can disable the native integration test, since we'll probably need to rework all of `optaplanner-benchmark` to get native to work.

**Comment by triceo** [comment]
I agree it is better to have a test without native than no test at all.
Still, we should make a decision if we want Benchmarker in native (which I think is questionable) and then decide about follow-up actions.

**Comment by ge0ffrey** [comment]
Merging with the native test disabled is good for me.
We indeed need to talk to the quarkus team that quarkus-optaplanner-benchmark does not support native, which can be a very difficult conversation. I'll open a topic on their zulip.

**Comment by ge0ffrey** [comment]
Quarkus discussion is here (out of scope for this PR):
https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/quarkus-optaplanner-benchmark.20does.20not.20support.20native

**Review by ge0ffrey — APPROVED** [review]

**Pull request merged**
