### PR TITLE
PLANNER-1219: Fix strategic oscillation bug

### PR DESCRIPTION
**Pull request by jordanovskijordan**
Fixes bug where a strategic oscillation move that improves a higher tier is picked over an improving move that does the improvement on a lower tier.

For example if the reference score is [0,-2,-3] the move with a score [-1,-1,-3] would be chosen over [0,-2,-1] which is an improving move.

See also : https://issues.jboss.org/browse/PLANNER-1219

### CODE REVIEW

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser3** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser3** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by ge0ffrey** [comment]
ok to test

**Comment by triceo** [comment]
jenkins please retest this

**Comment by triceo** [comment]
Closed in favor of #604, where I'm making code style changes to make the build green.
I have preserved the authorship of the original commit.

**Pull request closed without merging**
