### PR TITLE
Bump Quarkus 2.3.0.Final

### PR DESCRIPTION
**Pull request by radtriste**
Related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/1634
- https://github.com/kiegroup/optaplanner/pull/1593
- https://github.com/kiegroup/kogito-apps/pull/1044
- https://github.com/kiegroup/kogito-examples/pull/909
- https://github.com/kiegroup/optaplanner-quickstarts/pull/190
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/570

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>specific pull request build</b> please add comment: <b>Jenkins (re)run [optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] tests</b>
* for a <b>full downstream build</b> 
  * for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  * for <b>github actions</b> job: add the label `run_fdb`
* for a <b>compile downstream build</b> please add comment: <b>Jenkins run cdb</b>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* for an <b>upstream build</b> please add comment: <b>Jenkins run upstream</b>
* for a <b>Quarkus LTS check</b> please add comment: <b>Jenkins run LTS</b>
* for a <b>specific Quarkus LTS check</b> please add comment: <b>Jenkins (re)run [optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] LTS</b>
* for a <b>Native check</b> please add comment: <b>Jenkins run native</b>
* for a <b>specific Native LTS check</b> please add comment: <b>Jenkins (re)run [optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] native</b>
</details>

### CODE REVIEW

**Comment by radtriste** [comment]
@triceo Radovan is on holidays so putting you

**Review by triceo — APPROVED** [review]
Good when green.

**Comment by radtriste** [comment]
jenkins rerun kogito-examples tests

**Comment by radtriste** [comment]
created https://github.com/kiegroup/optaweb-vehicle-routing/pull/570 for optaweb failure

Jenkins rerun optaweb-vehicle-routing tests

**Comment by radtriste** [comment]
Jenkins rerun optaweb-vehicle-routing tests

**Comment by radtriste** [comment]
Jenkins rerun kogito-apps tests

**Comment by yurloc** [comment]
Jenkins rerun optaweb-vehicle-routing tests.

**Comment by yurloc** [comment]
@radtriste Unfortunately, you have to delete your `main-bump-quarkus-2.3.0.Final` branch first :slightly_frowning_face: 

[2021-10-01T13:18:38.204Z] [INFO]  [kiegroup/optaweb-vehicle-routing] Checking out project
[2021-10-01T13:18:38.204Z] [INFO]  [kiegroup/optaweb-vehicle-routing] Getting checkout Info. sourceProject: optaweb-vehicle-routing sourceGroup: radtriste. sourceBranch: main-bump-quarkus-2.3.0.Final. targetGroup: kiegroup. targetBranch: main. Mapping target: main
[2021-10-01T13:18:38.462Z] [INFO]  [kiegroup/optaweb-vehicle-routing] Merging https://github.com/kiegroup/optaweb-vehicle-routing:main into https://github.com/radtriste/optaweb-vehicle-routing:main-bump-quarkus-2.3.0.Final
[2021-10-01T13:18:41.041Z] [ERROR]  command git pull https://****@github.com/radtriste/optaweb-vehicle-routing main-bump-quarkus-2.3.0.Final failed with code 1. Error Message: hint: Pulling without specifying how to reconcile divergent branches is

**Comment by yurloc** [comment]
Jenkins rerun optaweb-vehicle-routing tests.

**Comment by radtriste** [comment]
Jenkins rerun kogito-apps tests

**Pull request merged**
