### PR TITLE
Override KIE group java conventions for OptaPlanner

### PR DESCRIPTION
**Pull request by rsynek**
Our code style differs from KIE group conventions on aligning method parameters. To avoid frequent comments on PRs about this code style difference, we should maintain our own code style definition.

### CODE REVIEW

**Comment by Christopher-Chianelli** [comment]
Why does this code style difference exists? Would this also apply to OptaWeb?

**Comment by rsynek** [comment]
@Christopher-Chianelli good questions;
"Why does this code style difference exists?"
There was a discussion about the code style in KIE group in the past - either this was an option that won or maybe it was not possible to enforce it for some other IDEs. I tried to look up the conversation, but haven't found it.
"Would this also apply to OptaWeb?" Depends on what we agree on. So far, I have seen this to be a struggle in PRs to OptaPlanner.

**Comment by ge0ffrey** [comment]
Agreed that this indentation difference has been a pita.

Good for me to merge this PR as a step forward,
but we need to standardize on the Quarkus code style (which is the defacto Java standard with Red Hat), enforce it in the build (like they do) and just be done with it:
- Here it is https://github.com/quarkusio/quarkus/tree/master/independent-projects/ide-config/src/main/resources (what, no IntelliJ code style files? Let's ask on zulip - I can't believe that)
- Here's how the build enforces it: https://github.com/quarkusio/quarkus/blob/master/build-parent/pom.xml#L320

**Comment by triceo** [comment]
@ge0ffrey Doesn't it make sense then to move to the Quarkus code style instead of using this PR?

**Comment by ge0ffrey** [comment]
Sure, I am happy to go there directly. But that will take a bit more work I imagine :)

**Comment by rsynek** [comment]
One more question about how far we want to go:
1) just publish the IntelliJ code style to make it easier for folks opening PRs to OptaPlanner (no matter if it's this code style or the one used in Quarkus)
2) enforce it via checkstyle and format the entire repository
3) spread it to OptaWeb projects as well

**Comment by ge0ffrey** [comment]
I believe: Yes, to 1), 2) and 3).

**Comment by Christopher-Chianelli** [comment]
Note: eclipse has a maven auto formatter plugin; Intellij does not

**Comment by rsynek** [comment]
> I believe: Yes, to 1), 2) and 3). Wydt?

It's the only way of achieving consistency across the projects. If we all agree on using that code style, it makes sense.

**Comment by triceo** [comment]
@rsynek Assuming I can get the Quarkus code style in IDEA, I say let's go for it.

**Comment by ge0ffrey** [comment]
@triceo I would be surprised if the Quarkus team haven't already done that. Note that the IDEA code styles are much more fine grained than Eclipse (Eclipse is a superset), so the Eclipse one doesn't define the IDEA one accuratly (but vica versa it does).

**Comment by triceo** [comment]
@ge0ffrey Their solution is to configure IDEA to use the Eclipse formatter:
https://github.com/quarkusio/quarkus/blob/master/CONTRIBUTING.md#idea-setup

**Comment by ge0ffrey** [comment]
> It's the only way of achieving consistency across the projects. If we all agree on using that code style, it makes sense.

Sounds good, as long as any voting is either in favor of using that code style or against it. Yes or no. No bikeshedding, no design by committee, no small variations, etc. I am putting my foot down on that. Other suggestions of well-accepted code styles in the Java ecosystem are welcome too - but again, no "tweaking" it.
Normally I don't believe in black-white acceptance voting like this, but 3+ previous experience with code style discussions make me force this exception...

**Comment by triceo** [comment]
Yeah, let's just take what Quarkus does without changes. I've looked at their code and there is nothing I would be fundamentally opposed to.

**Comment by rsynek** [comment]
Closing this PR, as its primary purpose was starting this discussion. I will open a new one with Quarkus code style. Hopefully in the next sprint.

Thanks everyone for your opinion!

**Pull request closed without merging**
