### PR TITLE
BXMSPROD-494 allow GA build on windows machine

### PR DESCRIPTION
**Pull request by Ginxo**
https://issues.redhat.com/browse/BXMSPROD-494

related to

https://github.com/kiegroup/lienzo-core/pull/133
https://github.com/kiegroup/lienzo-tests/pull/108
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1471
https://github.com/kiegroup/kie-soup/pull/158
https://github.com/kiegroup/appformer/pull/1054
https://github.com/kiegroup/droolsjbpm-knowledge/pull/465
https://github.com/kiegroup/drools/pull/3116
https://github.com/kiegroup/optaplanner/pull/940
https://github.com/kiegroup/jbpm/pull/1758
https://github.com/kiegroup/kie-jpmml-integration/pull/43
https://github.com/kiegroup/droolsjbpm-integration/pull/2243
https://github.com/kiegroup/openshift-drools-hacep/pull/100
https://github.com/kiegroup/droolsjbpm-tools/pull/118
https://github.com/kiegroup/kie-uberfire-extensions/pull/106
https://github.com/kiegroup/kie-wb-playground/pull/97
https://github.com/kiegroup/kie-wb-common/pull/3423
https://github.com/kiegroup/drools-wb/pull/1423
https://github.com/kiegroup/optaplanner-wb/pull/381
https://github.com/kiegroup/jbpm-designer/pull/891
https://github.com/kiegroup/jbpm-wb/pull/1461
https://github.com/kiegroup/jbpm-work-items/pull/153
https://github.com/kiegroup/kie-docs/pull/2849
https://github.com/kiegroup/optaweb-employee-rostering/pull/498
https://github.com/kiegroup/optaweb-vehicle-routing/pull/367
https://github.com/kiegroup/kie-wb-distributions/pull/1062

### CODE REVIEW

**Review by AntStephenson — APPROVED** [review]

**Comment by triceo** [comment]
@Ginxo This has now been open for 6 months. Do you have any plans to merge it, and if so, when?

**Comment by mareknovotny** [comment]
@triceo we would like to, but it seems windows build won't work on Appformer repository due maven GWT plugin limitations on file path limit to 256 characters.

But we changed the order of repository list so @Ginxo can rebase and try again to at least have windows CI for repositories before Appformer is built in our FDB. WDYT @Ginxo ?

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by Ginxo** [comment]
This was very very out of date, it was using build-chain@1.4, moved to @2.2 approach. Waiting for jobs completion to decide

**Comment by Ginxo** [comment]
@mareknovotny @triceo we can review/merge this PR

**Review by triceo — APPROVED** [review]
I am not a CI expert but I trust you - if you say this is the way forward, so be it.
Merge at will.

**Comment by triceo** [comment]
Just one comment though - this now builds on Ubuntu, not Windows. So I'm completely lost as to what is the point.

**Comment by Ginxo** [comment]
> Just one comment though - this now builds on Ubuntu, not Windows. So I'm completely lost as to what is the point.

@triceo you are right, my fault, flow adapted. Windows is now running. Thanks @triceo

**Review by mareknovotny — CHANGES_REQUESTED** [review]
long paths problem on windows, we need to add that block as on other PRs
```
 - name: Support longpaths
        if: ${{ matrix.os == 'windows-latest' }}
        run: git config --system core.longpaths true
```

**Comment by mareknovotny** [comment]
all green hooray!

**Review by mareknovotny — APPROVED** [review]

**Pull request merged**
