### PR TITLE
PLANNER-2194 Create a pipeline for building PRs

### PR DESCRIPTION
**Pull request by rsynek**
### JIRA
https://issues.redhat.com/browse/PLANNER-2194

### Checklist
- [ ] Documentation updated if applicable.
- [ ] Upgrade recipe provided if applicable.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>full downstream build</b> please add comment: <b>Jenkins run fdb</b>
* for a <b>compile downstream build</b> please add comment: <b>Jenkins run cdb</b>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* for an <b>upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by rsynek** [comment]
jenkins retest this

**Review by Ginxo — APPROVED** [review]
LGTM. It will probably be out once we have a centralized way to define project hierarchies and repository-list.txt file can be replaced by this
https://issues.jboss.org/browse/BXMSPROD-1025
It's fine for the moment.

**Comment by rsynek** [comment]
@triceo I am deactivating the old Jenkins job; feel free to merge this if you agree.

**Comment by Ginxo** [comment]
@triceo let me know if you want to revert it, I merged it without noticing your review was pending.

**Comment by triceo** [comment]
No, all is good.

**Pull request merged**
