### PR TITLE
Remove Java 8 from GHA

### PR DESCRIPTION
**Pull request by rsynek**
### Checklist
- [ ] Documentation updated if applicable.
- [ ] Upgrade recipe provided if applicable.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>specific pull request build</b> please add comment: <b>Jenkins (re)run [optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] tests</b>
* for a <b>full downstream build</b> please add comment: <b>Jenkins run fdb</b>
* for a <b>compile downstream build</b> please add comment: <b>Jenkins run cdb</b>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* for an <b>upstream build</b> please add comment: <b>Jenkins run upstream</b>
* for a <b>Quarkus LTS check</b> please add comment: <b>Jenkins run LTS</b>
* for a <b>specific Quarkus LTS check</b> please add comment: <b>Jenkins (re)run [optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] LTS</b>
* for a <b>Native check</b> please add comment: <b>Jenkins run native</b>
* for a <b>specific Native LTS check</b> please add comment: <b>Jenkins (re)run [optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] native</b>
</details>

### CODE REVIEW

**Comment by triceo** [comment]
I'm wondering... what is the point of OptaPlanner CI now? Build chain seems to be doing the same thing. (Other than OpenJDK 16.)

**Comment by rsynek** [comment]
> I'm wondering... what is the point of OptaPlanner CI now? Build chain seems to be doing the same thing. (Other than OpenJDK 16.)

There are several more things I am wondering, for example why I don't see the Jenkins builds anymore after we merged the previous PR that was supposed to fix the CI. Also, how did it work if the Build Chain CI was defined incorrectly?

**Comment by triceo** [comment]
Could Jenins just be broken, therefore unrelated?

**Comment by rsynek** [comment]
Jenkins run optaplanner tests

**Comment by rsynek** [comment]
> Could Jenkins just be broken, therefore unrelated?

That may be the case; let's give it a try.

**Comment by rsynek** [comment]
Jenkins run optaplanner tests

**Comment by rsynek** [comment]
I am going to fix the CI and then disable it in the Github UI until we agree on what we keep and what goes away.

**Review by triceo — APPROVED** [review]

**Comment by rsynek** [comment]
The CI has already passed, by was retriggered by changing the status from draft to ready for review. Merging without waiting for the second round.

**Pull request merged**
