### PR TITLE
PLANNER-2641 OptaPlanner depends on Drools, not Kogito 

### PR DESCRIPTION
**Pull request by triceo**
Upstream PR: https://github.com/kiegroup/kogito-pipelines/pull/351

### CODE REVIEW

**Comment by radtriste** [comment]
@triceo thanks for the PRs
Thinking that we don't need optaplanner downstream check from kogito-runtimes or? 
If yes, then we need a PR against kogito-runtimes and you can remove the optaplanner lines from https://github.com/kiegroup/kogito-runtimes/blob/main/.ci/jenkins/dsl/jobs.groovy#L26 :)

**Comment by triceo** [comment]
Will do, thanks for the pointer, @radtriste .

**Review by radtriste — APPROVED** [review]
lgtm

**Comment by triceo** [comment]
Jenkins retest this.

**Pull request merged**
