### PR TITLE
BXMSPROD-1546 updated native PR checks

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/BXMSPROD-1546

Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/328
- https://github.com/kiegroup/optaplanner/pull/1686

<details>
<summary>
How to replicate CI configuration locally?
</summary>

We do "simple" maven builds, they are just basically maven commands, but just because we have multiple repositories related between them and one change could affect several of those projects by multiple pull requests, we use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.

[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is not only a github-action tool but a CLI one, so in case you posted multiple pull requests related with this change you can easily reproduce the same build by executing it locally. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>specific pull request build</b> please add comment: <b>Jenkins (re)run [optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] tests</b>
* for a <b>full downstream build</b> 
  * for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  * for <b>github actions</b> job: add the label `run_fdb`
* for a <b>compile downstream build</b> please add comment: <b>Jenkins run cdb</b>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* for an <b>upstream build</b> please add comment: <b>Jenkins run upstream</b>
* for a <b>Quarkus LTS check</b> please add comment: <b>Jenkins run LTS</b>
* for a <b>specific Quarkus LTS check</b> please add comment: <b>Jenkins (re)run [optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] LTS</b>
* for a <b>Native check</b> please add comment: <b>Jenkins run native</b>
* for a <b>specific Native LTS check</b> please add comment: <b>Jenkins (re)run [optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] native</b>
</details>

### CODE REVIEW

**Comment by radtriste** [comment]
jenkins retest this

**Comment by radtriste** [comment]
jenkins run native tests

**Review by rsynek — APPROVED** [review]

**Comment by radtriste** [comment]
jenkins rerun optaplanner tests

**Comment by radtriste** [comment]
jenkins retest this

**Comment by radtriste** [comment]
jenkins rerun native

**Comment by radtriste** [comment]
jenkins run native

**Comment by radtriste** [comment]
jenkins retest this

**Comment by radtriste** [comment]
jenkins run native

**Comment by radtriste** [comment]
jenkins rerun kogito-apps tests

**Comment by radtriste** [comment]
jenkins rerun kogito-examples tests

**Comment by radtriste** [comment]
jenkins run native

**Comment by radtriste** [comment]
jenkins rerun kogito-examples tests

**Comment by radtriste** [comment]
jenkins rerun kogito-apps tests

**Comment by radtriste** [comment]
- kogito-apps build: `mvn [...] -Poptaplanner-downstream [...]`
- kogito-examples build: `mvn [...] -Poptaplanner-downstream [...]`
- kogito-apps native: `mvn [...] -Poptaplanner-downstream,native [...]`
- kogito-examples native: `mvn [...] -Poptaplanner-downstream-native [...]`

**Comment by radtriste** [comment]
DSL test should be ok once https://github.com/kiegroup/kogito-pipelines/pull/328 is merged

**Comment by Ginxo** [comment]
Jenkins retest this

**Comment by Ginxo** [comment]
Jenkins run native

**Comment by triceo** [comment]
FYI native tests will be failing now, due to another issue; I'm for merging this now.

**Comment by radtriste** [comment]
we need that change to have correct native PR checks.
Current PR checks are failing because the requested pull request config branch is not existing anymore
Merging as https://github.com/kiegroup/kogito-pipelines/pull/328 has been merged and tests were ok in previous run (apart from known native failures)

**Comment by radtriste** [comment]
Rebuild of jobs in progress: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/z-seed-optaplanner-job/182/

**Comment by radtriste** [comment]
jenkins run native

**Pull request merged**
