### PR TITLE
School timetabling slides

### PR DESCRIPTION
**Pull request by ge0ffrey**

### CODE REVIEW

**Comment by rsynek** [comment]
- the .svg files are missing the text when opened in a browser (at least for me), but Inkscape shows it correctly.
- why removing the schoolTimetablingArchitecture.png, if for the class diagram we keep the .png file?

**Comment by ge0ffrey** [comment]
Inkscape files use more advanced SVG features that don't work in browser or linux default svg viewer. As we use the SVG purely to not loose the source, but always use png's in publishing formats (adoc), that is workable. but indeed not ideal.

**Comment by ge0ffrey** [comment]
Good catch: schoolTimetablingArchitecture.png shouldn't be removed

**Comment by ge0ffrey** [comment]
Not sure why github diff was saying it was removed, because it wasn't on that branch and hasn't been since merging. Proof: https://github.com/kiegroup/optaplanner/blob/master/optaplanner-docs/src/main/asciidoc/QuickStart/SchoolTimetabling/schoolTimetablingArchitecture.png

**Pull request merged**
