### PR TITLE
[main] Bump Quarkus version to 2.6.0.CR1

### PR DESCRIPTION
**Pull request by radtriste**
Please review and merge

- https://github.com/kiegroup/kogito-pipelines/pull/337
- https://github.com/kiegroup/kogito-runtimes/pull/1775
- https://github.com/kiegroup/optaplanner/pull/1717
- https://github.com/kiegroup/kogito-apps/pull/1158
- https://github.com/kiegroup/optaplanner-quickstarts/pull/242
- https://github.com/kiegroup/kogito-examples/pull/1022

### CODE REVIEW

**Comment by radtriste** [comment]
jenkins retest this

**Comment by radtriste** [comment]
jenkins retest this

**Comment by radtriste** [comment]
jenkins retest this

**Comment by radtriste** [comment]
jenkins rerun kogito-apps tests

**Comment by radtriste** [comment]
jenkins rerun optaplanner-quickstarts tests

**Review by rsynek — APPROVED** [review]

**Comment by radtriste** [comment]
jenkins rerun optaplanner-quickstarts tests

**Comment by radtriste** [comment]
jenkins rerun optaweb-employee-rostering

**Comment by radtriste** [comment]
jenkins rerun optaplanner-quickstarts

**Comment by radtriste** [comment]
jenkins rerun optaweb-employee-rostering tests

**Comment by radtriste** [comment]
jenkins rerun optaplanner-quickstarts tests

**Comment by radtriste** [comment]
had to rebase -> https://github.com/kiegroup/optaplanner/pull/1736

**Pull request closed without merging**
