### PR TITLE
KOGITO-5532 Corrected PR check author handling

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/KOGITO-5532

Related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/1447
- https://github.com/kiegroup/optaplanner/pull/1432
- https://github.com/kiegroup/kogito-apps/pull/943
- https://github.com/kiegroup/kogito-examples/pull/798
- https://github.com/kiegroup/kogito-images/pull/597

### Checklist
- [ ] Documentation updated if applicable.
- [ ] Upgrade recipe provided if applicable.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>specific pull request build</b> please add comment: <b>Jenkins (re)run [optaplanner|apps|examples] tests</b>
* for a <b>full downstream build</b> please add comment: <b>Jenkins run fdb</b>
* for a <b>compile downstream build</b> please add comment: <b>Jenkins run cdb</b>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* for an <b>upstream build</b> please add comment: <b>Jenkins run upstream</b>
* for a <b>Quarkus LTS check</b> please add comment: <b>Jenkins run LTS</b>
* for a <b>specific Quarkus LTS check</b> please add comment: <b>Jenkins (re)run [optaplanner|apps|examples] LTS</b>
* for a <b>Native check</b> please add comment: <b>Jenkins run native</b>
* for a <b>specific Native LTS check</b> please add comment: <b>Jenkins (re)run [optaplanner|apps|examples] native</b>
</details>

### CODE REVIEW

**Review by danielezonca — APPROVED** [review]

**Review by ricardozanini — APPROVED** [review]

**Comment by ricardozanini** [comment]
jenkins rerun examples tests

**Comment by radtriste** [comment]
jenkins rerun examples tests

**Comment by radtriste** [comment]
jenkins rerun examples tests

**Comment by cristianonicolai** [comment]
Jenkins rerun examples tests

**Review by cristianonicolai — APPROVED** [review]

**Comment by radtriste** [comment]
Jenkins rerun examples tests

**Comment by radtriste** [comment]
`apps` error is unrelated to this change. See https://kie.zulipchat.com/#narrow/stream/232676-kogito/topic/.60testProcessInstanceIndex.60.20tests.20fail.20often.20on.20Jenkins

**Pull request merged**
