### PR TITLE
Complement JPMS requirements

### PR DESCRIPTION
**Pull request by mwkroening**
These steps are based on https://github.com/mwkroening/optaplanner-modulepath-example/commit/e8f909250a6664b368f55b6dd503bd2cc3240824
and https://github.com/psiroky/optaplanner-cloudbalancing-jdk9

The requirement to open up the two packages to all modules is really bothering me.
When opening the domain package only to `org.optaplanner.core`, I get this message:
```bash
Exception in thread "main" java.lang.IllegalAccessError: class org.drools.base.io.github.mwkroening.optaplannermodulepathexample.domain.CloudProcess520162288$getComputer (in unnamed module @0x4d68b571) cannot access class io.github.mwkroening.optaplannermodulepathexample.domain.CloudProcess (in module io.github.mwkroening.optaplannermodulepathexample) because module io.github.mwkroening.optaplannermodulepathexample does not export io.github.mwkroening.optaplannermodulepathexample.domain to unnamed module @0x4d68b571
	at org.drools.base.io.github.mwkroening.optaplannermodulepathexample.domain.CloudProcess520162288$getComputer.getValue(Unknown Source)
	at org.drools.core@7.18.0.Final/org.drools.core.base.extractors.BaseObjectClassFieldReader.getHashCode(BaseObjectClassFieldReader.java:180)
	at org.drools.core@7.18.0.Final/org.drools.core.base.ClassFieldReader.getHashCode(ClassFieldReader.java:224)
	at org.drools.core@7.18.0.Final/org.drools.core.util.AbstractHashTable$FieldIndex.hashCodeOf(AbstractHashTable.java:344)
	at org.drools.core@7.18.0.Final/org.drools.core.util.AbstractHashTable$SingleIndex.hashCodeOf(AbstractHashTable.java:409)
	at org.drools.core@7.18.0.Final/org.drools.core.util.index.TupleIndexHashTable.getOrCreate(TupleIndexHashTable.java:392)
	at org.drools.core@7.18.0.Final/org.drools.core.util.index.TupleIndexHashTable.add(TupleIndexHashTable.java:358)
	at org.drools.core@7.18.0.Final/org.drools.core.phreak.PhreakAccumulateNode.doRightInserts(PhreakAccumulateNode.java:217)
	at org.drools.core@7.18.0.Final/org.drools.core.phreak.PhreakAccumulateNode.doNode(PhreakAccumulateNode.java:85)
	at org.drools.core@7.18.0.Final/org.drools.core.phreak.RuleNetworkEvaluator.switchOnDoBetaNode(RuleNetworkEvaluator.java:581)
	at org.drools.core@7.18.0.Final/org.drools.core.phreak.RuleNetworkEvaluator.evalBetaNode(RuleNetworkEvaluator.java:552)
	at org.drools.core@7.18.0.Final/org.drools.core.phreak.RuleNetworkEvaluator.evalNode(RuleNetworkEvaluator.java:379)
	at org.drools.core@7.18.0.Final/org.drools.core.phreak.RuleNetworkEvaluator.innerEval(RuleNetworkEvaluator.java:339)
	at org.drools.core@7.18.0.Final/org.drools.core.phreak.RuleNetworkEvaluator.outerEval(RuleNetworkEvaluator.java:175)
	at org.drools.core@7.18.0.Final/org.drools.core.phreak.RuleNetworkEvaluator.evaluateNetwork(RuleNetworkEvaluator.java:133)
	at org.drools.core@7.18.0.Final/org.drools.core.phreak.RuleExecutor.reEvaluateNetwork(RuleExecutor.java:213)
	at org.drools.core@7.18.0.Final/org.drools.core.phreak.RuleExecutor.evaluateNetworkAndFire(RuleExecutor.java:88)
	at org.drools.core@7.18.0.Final/org.drools.core.concurrent.AbstractRuleEvaluator.internalEvaluateAndFire(AbstractRuleEvaluator.java:34)
	at org.drools.core@7.18.0.Final/org.drools.core.concurrent.SequentialRuleEvaluator.evaluateAndFire(SequentialRuleEvaluator.java:43)
	at org.drools.core@7.18.0.Final/org.drools.core.common.DefaultAgenda.fireLoop(DefaultAgenda.java:1062)
	at org.drools.core@7.18.0.Final/org.drools.core.common.DefaultAgenda.internalFireAllRules(DefaultAgenda.java:1009)
	at org.drools.core@7.18.0.Final/org.drools.core.common.DefaultAgenda.fireAllRules(DefaultAgenda.java:1001)
	at org.drools.core@7.18.0.Final/org.drools.core.impl.StatefulKnowledgeSessionImpl.internalFireAllRules(StatefulKnowledgeSessionImpl.java:1330)
	at org.drools.core@7.18.0.Final/org.drools.core.impl.StatefulKnowledgeSessionImpl.fireAllRules(StatefulKnowledgeSessionImpl.java:1321)
	at org.drools.core@7.18.0.Final/org.drools.core.impl.StatefulKnowledgeSessionImpl.fireAllRules(StatefulKnowledgeSessionImpl.java:1305)
	at org.optaplanner.core@7.18.0.Final/org.optaplanner.core.impl.score.director.drools.DroolsScoreDirector.calculateScore(DroolsScoreDirector.java:171)
	at org.optaplanner.core@7.18.0.Final/org.optaplanner.core.impl.solver.recaller.BestSolutionRecaller.solvingStarted(BestSolutionRecaller.java:69)
	at org.optaplanner.core@7.18.0.Final/org.optaplanner.core.impl.solver.AbstractSolver.solvingStarted(AbstractSolver.java:76)
	at org.optaplanner.core@7.18.0.Final/org.optaplanner.core.impl.solver.DefaultSolver.solvingStarted(DefaultSolver.java:210)
	at org.optaplanner.core@7.18.0.Final/org.optaplanner.core.impl.solver.DefaultSolver.solve(DefaultSolver.java:190)
	at io.github.mwkroening.optaplannermodulepathexample/io.github.mwkroening.optaplannermodulepathexample.App.main(App.java:22)
```
I dont't know if there is any way for Drools to make this call come from a named package.

The issue with the split package (https://github.com/x-stream/xstream/issues/120) seems to be dormant, although there has been some work to provide a combined artifact: https://github.com/xmlpull-xpp3/xmlpull-xpp3

I think the issue with the missing `java.scripting` module could be resolved by adding an `module-info.java` to OptaPlanner itself, so it can properly declare its dependency as per the java-contract:
https://twitter.com/johanvos/status/1094631555983728640

The only illegal reflective access of Drools in my test was this one:
```bash
WARNING: Illegal reflective access by org.drools.core.rule.builder.dialect.asm.ClassGenerator (file:/home/mkroening/.gradle/caches/modules-2/files-2.1/org.drools/drools-core/7.18.0.Final/ba6d99bb107cab6a9d798682f6487fdedba78dc/drools-core-7.18.0.Final.jar) to method protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError
```
I don't know if it would be possible to make Drools use the public API instead.

XStreams issue with illegal reflective acces (https://github.com/x-stream/xstream/issues/101) does not seem to make any progress. In my project I migrated from XStream to JAXB, which is supported on the modulepath.

Thanks for your help!

### CODE REVIEW

**Comment by kie-ci7** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by ge0ffrey** [comment]
ok to test

**Comment by ge0ffrey** [comment]
Merging this already, as this is the current status so it's good to have this documented.
That being said, we should indeed try to get rid of most of these hoops to jump through.

@mwkroening 

"I dont't know if there is any way for Drools to make this call come from a named package." -> Would you mind opening an issue for that on Drools? https://issues.jboss.org/browse/DROOLS
That's probably because Drools generates code at runtime. I do believe that ConstraintStreams will offer an advantage here over DRL as that will use the executable model so we can probably control the package from where those calls come from in OptaPlanner.
@mariofusco ^^ FYI

As for the XStream issues: fixing XPP3 and XMLPull by releasing 1.2.0 would fix a lot of XStream pain in my opinion, see this discussion: https://groups.google.com/forum/#!topic/xstream-user/CILJGN_vN1w

**Comment by mwkroening** [comment]
Issue for Drools' unnamed module: [DROOLS-3766](https://issues.jboss.org/browse/DROOLS-3766)

I just read about Constraint streams in the docs. That surely sounds promising!

**Pull request merged**
