### PR TITLE
Reproducer for PLANNER-642: modified vehicle routing example (not fix)

### PR DESCRIPTION
**Pull request by nbolleboom**
Modified vehicle routing example to reproduce distance matrix problem (created pull request per request of Geoffrey, see https://issues.jboss.org/browse/PLANNER-642)

### CODE REVIEW

**Comment by ge0ffrey** [comment]
Thanks :)

**Comment by ge0ffrey** [comment]
ok to test
Not sure why jenkins is going nuts here. Sorry for the spam

**Comment by psiroky** [comment]
This is the reason https://github.com/jenkinsci/ghprb-plugin/issues/267 and this is a proposed fix https://github.com/jenkinsci/ghprb-plugin/pull/533 (unmerged).

**Comment by ge0ffrey** [comment]
Thank you the PR.

Nonetheless, I am closing this PR for now because I currently see no clear way of resolving this beyond the workaround discussed in the jira. It seems to be a natural part of the nearby selection behavior. Until we have a good proposal on how to deal with this problem, I don't want this to linger in the "open PR" list for another x months - as we have a strong policy to merge PR's ASAP (and we can't merge this one currently).
I am keeping the PR link in jira so we can revisit this reproducer once we figure out a way to deal with it. Please don't remove the branch on your fork.
The simplified VRP work that is coming soon, as well as the mixed VRP support, is probably going to open new doors (including the buoy CH), all of which might lead to opportunities for the nearby selection design.

**Pull request closed without merging**
