### PR TITLE
PLANNER-2836 Deprecate XStream

### PR DESCRIPTION
**Pull request by triceo**

### CODE REVIEW

**Comment by kie-ci3** [comment]
**(tests) - optaplanner job** `#598` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/main/job/pullrequest/job/optaplanner.tests.optaplanner/598/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-11-27T13:19:47.660Z] [INFO] Getting build-chain version from composite action file<br/>[Pipeline] readFile<br/>[Pipeline] echo<br/>[2022-11-27T13:19:47.879Z] [INFO] build-chain version recovered '2.3.36'<br/>[Pipeline] sh<br/>[2022-11-27T13:19:48.164Z] + npm install -g @kie/build-chain-action@2.3.36 -registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/<br/>[2022-11-27T13:21:09.519Z] npm ERR! code E503<br/>[2022-11-27T13:21:09.519Z] npm ERR! 503 Service Unavailable - GET https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/@kie%2fbuild-chain-action<br/>[2022-11-27T13:21:09.519Z] <br/>[2022-11-27T13:21:09.519Z] npm ERR! A complete log of this run can be found in:<br/>[2022-11-27T13:21:09.519Z] npm ERR!     /home/jenkins/.npm/_logs/2022-11-27T13_20_58_499Z-debug.log<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build quarkus)<br/>Stage "Build quarkus" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build quarkus platform)<br/>Stage "Build quarkus platform" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>Stage "Build projects" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Sonar analysis)<br/>Stage "Sonar analysis" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space after build)<br/>Stage "check space after build" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-11-27T13:21:10.465Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/main/job/pullrequest/job/optaplanner.tests.optaplanner/598/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci3** [comment]
**(tests) - optaplanner-quickstarts job** `#599` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/main/job/pullrequest/job/optaplanner.tests.downstream.optaplanner-quickstarts/599/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-11-27T13:20:47.153Z] [INFO] Getting build-chain version from composite action file<br/>[Pipeline] readFile<br/>[Pipeline] echo<br/>[2022-11-27T13:20:47.257Z] [INFO] build-chain version recovered '2.3.36'<br/>[Pipeline] sh<br/>[2022-11-27T13:20:47.541Z] + npm install -g @kie/build-chain-action@2.3.36 -registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/<br/>[2022-11-27T13:22:08.894Z] npm ERR! code E503<br/>[2022-11-27T13:22:08.894Z] npm ERR! 503 Service Unavailable - GET https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/@kie%2fbuild-chain-action<br/>[2022-11-27T13:22:08.894Z] <br/>[2022-11-27T13:22:08.894Z] npm ERR! A complete log of this run can be found in:<br/>[2022-11-27T13:22:08.894Z] npm ERR!     /home/jenkins/.npm/_logs/2022-11-27T13_21_57_460Z-debug.log<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build quarkus)<br/>Stage "Build quarkus" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build quarkus platform)<br/>Stage "Build quarkus platform" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>Stage "Build projects" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Sonar analysis)<br/>Stage "Sonar analysis" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space after build)<br/>Stage "check space after build" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-11-27T13:22:09.922Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/main/job/pullrequest/job/optaplanner.tests.downstream.optaplanner-quickstarts/599/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci3** [comment]
**(tests) - optaweb-vehicle-routing job** `#593` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/main/job/pullrequest/job/optaplanner.tests.downstream.optaweb-vehicle-routing/593/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-11-27T13:20:57.537Z] [INFO] Getting build-chain version from composite action file<br/>[Pipeline] readFile<br/>[Pipeline] echo<br/>[2022-11-27T13:20:57.643Z] [INFO] build-chain version recovered '2.3.36'<br/>[Pipeline] sh<br/>[2022-11-27T13:20:57.924Z] + npm install -g @kie/build-chain-action@2.3.36 -registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/<br/>[2022-11-27T13:22:19.286Z] npm ERR! code E503<br/>[2022-11-27T13:22:19.286Z] npm ERR! 503 Service Unavailable - GET https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/@kie%2fbuild-chain-action<br/>[2022-11-27T13:22:19.286Z] <br/>[2022-11-27T13:22:19.286Z] npm ERR! A complete log of this run can be found in:<br/>[2022-11-27T13:22:19.286Z] npm ERR!     /home/jenkins/.npm/_logs/2022-11-27T13_22_07_076Z-debug.log<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build quarkus)<br/>Stage "Build quarkus" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build quarkus platform)<br/>Stage "Build quarkus platform" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>Stage "Build projects" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Sonar analysis)<br/>Stage "Sonar analysis" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space after build)<br/>Stage "check space after build" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-11-27T13:22:20.246Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/main/job/pullrequest/job/optaplanner.tests.downstream.optaweb-vehicle-routing/593/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci3** [comment]
**(tests) - optaplanner-quickstarts job** `#600` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/main/job/pullrequest/job/optaplanner.tests.downstream.optaplanner-quickstarts/600/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-11-27T13:30:14.736Z] [INFO] Getting build-chain version from composite action file<br/>[Pipeline] readFile<br/>[Pipeline] echo<br/>[2022-11-27T13:30:14.944Z] [INFO] build-chain version recovered '2.3.36'<br/>[Pipeline] sh<br/>[2022-11-27T13:30:15.223Z] + npm install -g @kie/build-chain-action@2.3.36 -registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/<br/>[2022-11-27T13:31:36.559Z] npm ERR! code E503<br/>[2022-11-27T13:31:36.559Z] npm ERR! 503 Service Unavailable - GET https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/@kie%2fbuild-chain-action<br/>[2022-11-27T13:31:36.559Z] <br/>[2022-11-27T13:31:36.559Z] npm ERR! A complete log of this run can be found in:<br/>[2022-11-27T13:31:36.559Z] npm ERR!     /home/jenkins/.npm/_logs/2022-11-27T13_31_24_316Z-debug.log<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build quarkus)<br/>Stage "Build quarkus" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build quarkus platform)<br/>Stage "Build quarkus platform" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>Stage "Build projects" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Sonar analysis)<br/>Stage "Sonar analysis" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space after build)<br/>Stage "check space after build" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-11-27T13:31:37.524Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/main/job/pullrequest/job/optaplanner.tests.downstream.optaplanner-quickstarts/600/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci3** [comment]
**(tests) - optaweb-vehicle-routing job** `#594` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/main/job/pullrequest/job/optaplanner.tests.downstream.optaweb-vehicle-routing/594/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-11-27T13:30:14.767Z] [INFO] Getting build-chain version from composite action file<br/>[Pipeline] readFile<br/>[Pipeline] echo<br/>[2022-11-27T13:30:14.941Z] [INFO] build-chain version recovered '2.3.36'<br/>[Pipeline] sh<br/>[2022-11-27T13:30:15.222Z] + npm install -g @kie/build-chain-action@2.3.36 -registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/<br/>[2022-11-27T13:31:36.563Z] npm ERR! code E503<br/>[2022-11-27T13:31:36.563Z] npm ERR! 503 Service Unavailable - GET https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/@kie%2fbuild-chain-action<br/>[2022-11-27T13:31:36.563Z] <br/>[2022-11-27T13:31:36.563Z] npm ERR! A complete log of this run can be found in:<br/>[2022-11-27T13:31:36.563Z] npm ERR!     /home/jenkins/.npm/_logs/2022-11-27T13_31_25_578Z-debug.log<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build quarkus)<br/>Stage "Build quarkus" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build quarkus platform)<br/>Stage "Build quarkus platform" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>Stage "Build projects" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Sonar analysis)<br/>Stage "Sonar analysis" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space after build)<br/>Stage "check space after build" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-11-27T13:31:37.522Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/main/job/pullrequest/job/optaplanner.tests.downstream.optaweb-vehicle-routing/594/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci3** [comment]
**(tests) - optaplanner job** `#599` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/main/job/pullrequest/job/optaplanner.tests.optaplanner/599/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-11-27T13:30:14.924Z] [INFO] Getting build-chain version from composite action file<br/>[Pipeline] readFile<br/>[Pipeline] echo<br/>[2022-11-27T13:30:15.000Z] [INFO] build-chain version recovered '2.3.36'<br/>[Pipeline] sh<br/>[2022-11-27T13:30:15.279Z] + npm install -g @kie/build-chain-action@2.3.36 -registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/<br/>[2022-11-27T13:31:36.627Z] npm ERR! code E503<br/>[2022-11-27T13:31:36.627Z] npm ERR! 503 Service Unavailable - GET https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/@kie%2fbuild-chain-action<br/>[2022-11-27T13:31:36.627Z] <br/>[2022-11-27T13:31:36.627Z] npm ERR! A complete log of this run can be found in:<br/>[2022-11-27T13:31:36.627Z] npm ERR!     /home/jenkins/.npm/_logs/2022-11-27T13_31_25_191Z-debug.log<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build quarkus)<br/>Stage "Build quarkus" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build quarkus platform)<br/>Stage "Build quarkus platform" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>Stage "Build projects" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Sonar analysis)<br/>Stage "Sonar analysis" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space after build)<br/>Stage "check space after build" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-11-27T13:31:37.589Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/main/job/pullrequest/job/optaplanner.tests.optaplanner/599/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci3** [comment]
**(tests) - optaplanner-quickstarts job** `#601` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/main/job/pullrequest/job/optaplanner.tests.downstream.optaplanner-quickstarts/601/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-11-27T20:10:29.558Z] [INFO] Getting build-chain version from composite action file<br/>[Pipeline] readFile<br/>[Pipeline] echo<br/>[2022-11-27T20:10:29.797Z] [INFO] build-chain version recovered '2.3.36'<br/>[Pipeline] sh<br/>[2022-11-27T20:10:30.080Z] + npm install -g @kie/build-chain-action@2.3.36 -registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/<br/>[2022-11-27T20:11:51.425Z] npm ERR! code E503<br/>[2022-11-27T20:11:51.425Z] npm ERR! 503 Service Unavailable - GET https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/@kie%2fbuild-chain-action<br/>[2022-11-27T20:11:51.425Z] <br/>[2022-11-27T20:11:51.425Z] npm ERR! A complete log of this run can be found in:<br/>[2022-11-27T20:11:51.425Z] npm ERR!     /home/jenkins/.npm/_logs/2022-11-27T20_11_39_390Z-debug.log<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build quarkus)<br/>Stage "Build quarkus" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build quarkus platform)<br/>Stage "Build quarkus platform" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>Stage "Build projects" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Sonar analysis)<br/>Stage "Sonar analysis" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space after build)<br/>Stage "check space after build" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-11-27T20:11:52.262Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/main/job/pullrequest/job/optaplanner.tests.downstream.optaplanner-quickstarts/601/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci3** [comment]
**(tests) - optaweb-vehicle-routing job** `#595` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/main/job/pullrequest/job/optaplanner.tests.downstream.optaweb-vehicle-routing/595/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-11-27T20:11:59.096Z] [INFO] Getting build-chain version from composite action file<br/>[Pipeline] readFile<br/>[Pipeline] echo<br/>[2022-11-27T20:11:59.345Z] [INFO] build-chain version recovered '2.3.36'<br/>[Pipeline] sh<br/>[2022-11-27T20:11:59.624Z] + npm install -g @kie/build-chain-action@2.3.36 -registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/<br/>[2022-11-27T20:13:20.963Z] npm ERR! code E503<br/>[2022-11-27T20:13:20.963Z] npm ERR! 503 Service Unavailable - GET https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/@kie%2fbuild-chain-action<br/>[2022-11-27T20:13:20.963Z] <br/>[2022-11-27T20:13:20.963Z] npm ERR! A complete log of this run can be found in:<br/>[2022-11-27T20:13:20.963Z] npm ERR!     /home/jenkins/.npm/_logs/2022-11-27T20_13_08_908Z-debug.log<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build quarkus)<br/>Stage "Build quarkus" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build quarkus platform)<br/>Stage "Build quarkus platform" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>Stage "Build projects" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Sonar analysis)<br/>Stage "Sonar analysis" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space after build)<br/>Stage "check space after build" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-11-27T20:13:21.826Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/main/job/pullrequest/job/optaplanner.tests.downstream.optaweb-vehicle-routing/595/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci3** [comment]
**(tests) - optaplanner job** `#600` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/main/job/pullrequest/job/optaplanner.tests.optaplanner/600/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-11-27T20:13:28.659Z] [INFO] Getting build-chain version from composite action file<br/>[Pipeline] readFile<br/>[Pipeline] echo<br/>[2022-11-27T20:13:28.758Z] [INFO] build-chain version recovered '2.3.36'<br/>[Pipeline] sh<br/>[2022-11-27T20:13:29.035Z] + npm install -g @kie/build-chain-action@2.3.36 -registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/<br/>[2022-11-27T20:14:50.468Z] npm ERR! code E503<br/>[2022-11-27T20:14:50.468Z] npm ERR! 503 Service Unavailable - GET https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/@kie%2fbuild-chain-action<br/>[2022-11-27T20:14:50.468Z] <br/>[2022-11-27T20:14:50.469Z] npm ERR! A complete log of this run can be found in:<br/>[2022-11-27T20:14:50.469Z] npm ERR!     /home/jenkins/.npm/_logs/2022-11-27T20_14_38_390Z-debug.log<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build quarkus)<br/>Stage "Build quarkus" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build quarkus platform)<br/>Stage "Build quarkus platform" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>Stage "Build projects" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Sonar analysis)<br/>Stage "Sonar analysis" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space after build)<br/>Stage "check space after build" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-11-27T20:14:51.299Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/main/job/pullrequest/job/optaplanner.tests.optaplanner/600/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Review by rsynek — APPROVED** [review]
LGTM. Good that we no longer use XStream for Benchmark results.

**Pull request merged**
