### PR TITLE
PLANNER-1311 Upgrade optaplanner-persistence-jpa to work with hibernate 5.3+ (superseeded by other)

### PR DESCRIPTION
**Pull request by ge0ffrey**
Requires kie-parent or ip-bom changes by @mbiarnes that upgrade us to hibernate 5.3 (and dependencies like net.bytebuddy too). But without these changes, he won't be able to merge his changes either.

### CODE REVIEW

**Comment by mbiarnes** [comment]
[ERRAI-1118](https://issues.jboss.org/browse/ERRAI-1118?filter=-2)

**Comment by rsynek** [comment]
The failed test is not connected and should be fixed by now.

**Comment by rsynek** [comment]
jenkins retest this

**Comment by rsynek** [comment]
jenkins retest this

**Comment by ge0ffrey** [comment]
Closing in favor of this duplicate: https://github.com/kiegroup/optaplanner/pull/459

**Pull request closed without merging**
