### PR TITLE
Use solver XSD in tests + move bavetSolverConfig.xml in same package as test

### PR DESCRIPTION
**Pull request by ge0ffrey**

### CODE REVIEW

**Review by rsynek — APPROVED** [review]

**Comment by rsynek** [comment]
jenkins retest this

**Review by Christopher-Chianelli — APPROVED** [review]

**Comment by Christopher-Chianelli** [comment]
Looking at the failed tests in FDB, it appears Maintenance Scheduling quickstart does not get a feasible solution in tests; seems unrelated to this change.

**Comment by rsynek** [comment]
@Christopher-Chianelli  yes, I wonder if it may be caused by the same issue which resulted in https://github.com/kiegroup/optaplanner/pull/1263. Now, after that PR has been merged, there is one easy way to tell.

**Comment by rsynek** [comment]
jenkins retest this

**Pull request merged**
