### PR TITLE
BAQE-1696 - Change revapi to check against 7.48.0.Final

### PR DESCRIPTION
**Pull request by MarianMacik**
**JIRA:** [BAQE-1696](https://issues.redhat.com/browse/BAQE-1696)

depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1585

### CODE REVIEW

**Comment by MarianMacik** [comment]
jenkins retest this

**Review by afalhambra — APPROVED** [review]
LGTM

**Comment by triceo** [comment]
FYI GHA failed because Revapi is apparently missing some ignores.
Not sure how come that Jenkins is green.

**Comment by MarianMacik** [comment]
@triceo GHA doesn't see the change in the kie-parent I think. This has always been like that in OptaPlanner.

**Pull request merged**
