### PR TITLE
PLANNER-1853: Add a FlatZinc -> OptaPlanner model + constraints compiler

### PR DESCRIPTION
**Pull request by Christopher-Chianelli**
MiniZinc has a proper subset FlatZinc (which is much simpler), which can be used for mapping Constraint Solvers to MiniZinc (https://www.minizinc.org/doc-2.4.3/en/fzn-spec.html). 

Current progress: Frontend (Tokenizer + Parser -> IR) is done. Created the compiler using https://javacc.github.io/javacc/ (which is also used in JavaParser; license BSD License 2.0). 

Future work: IR -> OptaPlanner model + constraints using GIZMO.

### JIRA

https://issues.redhat.com/browse/PLANNER-1853

### Checklist
- [ ] Documentation updated if applicable.
- [ ] Upgrade recipe provided if applicable.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>specific pull request build</b> please add comment: <b>Jenkins (re)run [optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] tests</b>
* for a <b>full downstream build</b> please add comment: <b>Jenkins run fdb</b>
* for a <b>compile downstream build</b> please add comment: <b>Jenkins run cdb</b>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* for an <b>upstream build</b> please add comment: <b>Jenkins run upstream</b>
* for a <b>Quarkus LTS check</b> please add comment: <b>Jenkins run LTS</b>
* for a <b>specific Quarkus LTS check</b> please add comment: <b>Jenkins (re)run [optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] LTS</b>
* for a <b>Native check</b> please add comment: <b>Jenkins run native</b>
* for a <b>specific Native LTS check</b> please add comment: <b>Jenkins (re)run [optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] native</b>
</details>

### CODE REVIEW

**Comment by Christopher-Chianelli** [comment]
We would need constraint "templates" for the following predicates: https://www.minizinc.org/doc-2.5.5/en/lib-flatzinc.html

**Comment by ge0ffrey** [comment]
This is a very interesting experiment in which Chris is investing time, but we need to think long and hard before we merge it and we sign up to support and maintain this through the years. Is it worth it?
Minizinc isn't OO nor FP friendly. To assign employees to shifts, you can't create a Shift with a variable of type Employee (not OO friendly). To penalize bad shifts assignments, the constraints can't call existing code (not FP friendly).

**Comment by Christopher-Chianelli** [comment]
Update: Three Color works (as in, given a FlatZinc file, it will parse it, create the model and constraints,  solve it, and return a solution that passes all the constraints).

**Comment by ge0ffrey** [comment]
Closing the MiniZinc translator because we don't want to pursue this further.

**Pull request closed without merging**
