### PR TITLE
KOGITO-6130 Upgrade to Quarkus 2.4.2

### PR DESCRIPTION
**Pull request by cristianonicolai**
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/1695
- https://github.com/kiegroup/kogito-apps/pull/1095
- https://github.com/kiegroup/kogito-examples/pull/940
- https://github.com/kiegroup/optaplanner/pull/1658
- https://github.com/kiegroup/optaplanner-quickstarts/pull/220

### CODE REVIEW

**Review by evacchi — COMMENTED** [review]
I think 2.4.2 is about to be released, see https://github.com/quarkusio/quarkus/issues/20846

**Comment by radtriste** [comment]
Please use the `*-update-quarkus` jobs from https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/tools/
There are 4 jobs to run to make that update (yeah I know we need a main job to call the others, it would be easier ...)

**Comment by triceo** [comment]
jenkins retest this

**Comment by radtriste** [comment]
> Please use the `*-update-quarkus` jobs from https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/tools/ There are 4 jobs to run to make that update (yeah I know we need a main job to call the others, it would be easier ...)

nevermind it only misses the update on optaplanner-quickstarts

**Review by tiagodolphine — APPROVED** [review]

**Comment by cristianonicolai** [comment]
@evacchi done

**Review by radtriste — APPROVED** [review]

**Pull request merged**
