### PR TITLE
[AF-1555]: Upgraded WF11 to WF14

### PR DESCRIPTION
**Pull request by adrielparedes**
## Description

Upgrate to Wildfly 14

@ge0ffrey Would you mind to review it?

## Related to:
* https://github.com/jboss-integration/jboss-integration-platform-bom/pull/427
* https://github.com/errai/errai/pull/363
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/843
* https://github.com/kiegroup/appformer/pull/483
* https://github.com/kiegroup/kie-wb-common/pull/2147
* https://github.com/kiegroup/jbpm/pull/1336
* https://github.com/kiegroup/jbpm-wb/pull/1206
* https://github.com/kiegroup/drools/pull/2086
* https://github.com/kiegroup/droolsjbpm-integration/pull/1583
* https://github.com/kiegroup/kie-wb-distributions/pull/821 
* https://github.com/kiegroup/kie-docs/pull/1108
*https://github.com/kiegroup/optaplanner/pull/437
*https://github.com/kiegroup/optaplanner-wb/pull/304

### CODE REVIEW

**Comment by rsynek** [comment]
@ge0ffrey yes, I ran it locally and the test passed.

**Comment by ge0ffrey** [comment]
Looks good to me.

**Comment by adrielparedes** [comment]
jenkins retest this

**Comment by adrielparedes** [comment]
jenkins retest this

**Comment by rsynek** [comment]
@ge0ffrey @adrielparedes  is this PR ready to be merged?

**Pull request merged**
