### PR TITLE
PLANNER-1845 operationsQueue.clear() during destroy: document why not

### PR DESCRIPTION
**Pull request by ge0ffrey**

### CODE REVIEW

**Comment by ge0ffrey** [comment]
ow crap, I messed up this PR

**Comment by ge0ffrey** [comment]
Should be good now

**Comment by ge0ffrey** [comment]
@triceo The linux build is red - are we sure this was safe to merge? Not that I mind the merge :)
Just saying that I haven't run all the tests locally (given that this is a small PR - for big ones I do), relying on jenkins to do that for me, just the related tests.

**Comment by triceo** [comment]
Damn me, I completely forgot to check the CI results, @ge0ffrey.
I built master locally and it works, therefore I assume the CI failure isn't us.
 (Don't have VPN now.)

**Pull request merged**
