### PR TITLE
Docs review chapter repeated planning

### PR DESCRIPTION
**Pull request by gsheldon**
First run through of the Repeated Planning chapter.

The ProblemFactChange section was particularly tricky. This might need a pretty good review, since I wasn't sure about a lot of this content. This was just a first run through, please let me know where I've gone totally wrong and I'll fix it up.

Thanks.

### CODE REVIEW

**Comment by ge0ffrey** [comment]
Hi Gemma, there are conflicts on this PR, probably due to changes that meanwhile happened on this chapter as from when you started working on it. Can you do a "git fetch upstream" and "gitk" to see which commits are on master but not on you yet, and then rebase to master (and fix any merge conflicts)?

**Comment by gsheldon** [comment]
Sorry Geoffrey! Hopefully this is ok now?

**Comment by ge0ffrey** [comment]
@gsheldon It still says "This branch cannot be rebased due to conflicts", however squashing is possible. But it says it's squashing 57 commits(!).
So I started analyzing what's going on. Here's what I got so far:

The blessed history of master [1] says:
  - 3 April: changed numerals ...
  - 26 Mar: Move image into ...

Your fork's history of that branch says [2]: 
  - ... (7 commits)
  - 3 April: changed numerals ...
  - 26 Mar: Move image into ...

What's going on with those other 50 commits?

[1] https://github.com/kiegroup/optaplanner/commits/master/optaplanner-docs/src/main/asciidoc/RepeatedPlanning/RepeatedPlanning-chapter.adoc
[2] https://github.com/gsheldon/optaplanner/commits/DocsReview-chapterRepeatedPlanning/optaplanner-docs/src/main/asciidoc/RepeatedPlanning/RepeatedPlanning-chapter.adoc

**Comment by gsheldon** [comment]
Honestly, I don't even know at this point.

I've tried resolving the merge conflicts repeatedly and it said there were
no conflicts the last time I committed.

I'll try to figure it out tomorrow.

**Comment by ge0ffrey** [comment]
Yea, it's strange. What I advice to try is the following:

1) checkout a new branch from your current branch (just so you have a backup)
2) squash those 7 commits into one. You can do that with "git rebase -i HEAD^10". The -i will give you an interactive way to decide which to squash. See this video: https://www.youtube.com/watch?v=msuJGG2iWjs
3) Submit that squashed commit as a new PR.
4) Optionally you can even just checkout the latest upsteam master ("git fetch upstream" first!) again in a new branch and cherry pick that one big squashed commit in that new branch. That really guarantees a clean slate.

In any case, once all your changes are merged in blessed (not sooner or you'll lose data), it might not be a bad idea delete your fork and create it again (and your local clones).

**Comment by ge0ffrey** [comment]
Merged through https://github.com/kiegroup/optaplanner/pull/323 so closing this one

**Pull request closed without merging**
