### PR TITLE
Add logic to prevent arithmetic overflow of nearby entity count limit

### PR DESCRIPTION
**Pull request by Woodz**
Resolve: PLANNER-1225

### CODE REVIEW

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by Woodz** [comment]
This is a hotfix for 7.0.0 but should also be applied to master and any other legacy hotfix branches

**Comment by ge0ffrey** [comment]
Thanks @Woodz - nice work

**Comment by ge0ffrey** [comment]
@rsynek I think the combination of BetaDistributionNearbyRandom and discardNearbyIndexZero=true isn't unit tested, otherwise we'd have seen this already. Overall, our unit testing of nearby selection is weak (none of the examples have it activated).

The main reason it's not activated in the examples, is because we don't want it to happen for small datasets. So we need an auto-tuning feature - which I haven't had time to work on yet. None the less, regardless, it's probably a good idea that we build some integration like tests around this for like we have for multithreaded solving? Wdyt?

**Comment by rsynek** [comment]
@ge0ffrey I'm not sure this issue could be caught by an integration test. Best start is usually writing unit tests guided by a coverage report. We already have it in our backlog https://issues.jboss.org/browse/PLANNER-544. Covering many different combinations by integration tests is expensive, thus I would rather build it on top of a solid unit coverage.

**Pull request merged**
